/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.linkedin.venice.kafka.protocol;

@SuppressWarnings("all")
@org.apache.avro.specific.FixedSize(16)
public class GUID extends org.apache.avro.specific.SpecificFixed {}
