package com.linkedin.venice.schema;

import com.linkedin.venice.schema.avro.DirectionalSchemaCompatibilityType;
import com.linkedin.venice.utils.AvroSchemaUtils;
import org.apache.avro.Schema;
import org.testng.Assert;
import org.testng.annotations.Test;

public class TestSchemaData {
  @Test
  public void testAddKeySchema() {
    String keySchemaStr = "\"string\"";
    int id = 1;
    SchemaEntry entry = new SchemaEntry(id, keySchemaStr);
    SchemaData schemaData = new SchemaData("test_store");
    schemaData.setKeySchema(entry);

    SchemaEntry keySchema = schemaData.getKeySchema();
    Assert.assertEquals(keySchema.getId(), 1);
    Assert.assertEquals(keySchemaStr, keySchema.getSchema().toString());
  }

  @Test
  public void  testSuperSetSchemaDefaultCompatibility() {
     String valueSchemaStr1 = "{\n" + "  \"type\": \"record\",\n" + "  \"name\": \"memberFeaturesObject\",\n"
         + "  \"namespace\": \"com.linkedin.pymk.schema\",\n" + "  \"fields\": [\n" + "    {\n"
         + "      \"name\": \"activityLevel\",\n" + "      \"type\": \"int\",\n"
         + "      \"doc\": \"Member activity level, from 0-4. 0-4 means: 0(Onboarding), 1(Dormant), 2(OneByOne), 3(OneByThree), 4(FourbyFour)\",\n"
         + "      \"default\": -1\n" + "    },\n" + "    {\n" + "      \"name\": \"connectionCount\",\n"
         + "      \"type\": \"int\",\n" + "      \"doc\": \"The total connection count of a member.\",\n"
         + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"lastConnectionAcceptedAt\",\n"
         + "      \"type\": \"int\",\n"
         + "      \"doc\": \"The Unix timestamp (seconds) of the most recently accepted connection.\",\n"
         + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"invReceivedCount\",\n"
         + "      \"type\": \"int\",\n"
         + "      \"doc\": \"The number of member connection invitations received by the member in the past 28 days.\",\n"
         + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"pymkSourceImpressionCount\",\n"
         + "      \"type\": \"int\",\n"
         + "      \"doc\": \"The number of pymk impressions viewed by a viewer in 56 days happened 60 days ago.\",\n"
         + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"pymkDestImpressionCount\",\n"
         + "      \"type\": \"int\",\n"
         + "      \"doc\": \"The number of pymk impressions being viewed by a viewee in 56 days happened 60 days ago.\",\n"
         + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"sourceInvitationCount\",\n"
         + "      \"type\": \"int\",\n"
         + "      \"doc\": \"The number of generic invitations sent by a source member in 56 days happened 60 days ago.\",\n"
         + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"destInvitationCount\",\n"
         + "      \"type\": \"int\",\n"
         + "      \"doc\": \"The number of generic invitations received by a dest member in 56 days happened 60 days ago.\",\n"
         + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"pymkSourceInvitationCount\",\n"
         + "      \"type\": \"int\",\n"
         + "      \"doc\": \"The number of pymk invitations sent by a source member in 56 days happened 60 days ago.\",\n"
         + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"pymkDestInvitationCount\",\n"
         + "      \"type\": \"int\",\n"
         + "      \"doc\": \"The number of pymk invitations received by a dest member in 56 days happened 60 days ago.\",\n"
         + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"sourceInvitationAcceptCount\",\n"
         + "      \"type\": \"int\",\n"
         + "      \"doc\": \"The number of accepted generic invitations sent by a source member since 56 days ahead of 60 days ago.\",\n"
         + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"destInvitationAcceptCount\",\n"
         + "      \"type\": \"int\",\n"
         + "      \"doc\": \"The number of accepted generic invitations received by a dest member since 56 days ahead of 60 days ago.\",\n"
         + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"pymkSourceInvitationAcceptCount\",\n"
         + "      \"type\": \"int\",\n"
         + "      \"doc\": \"The number of accepted pymk invitations sent by a source member since 56 days ahead of 60 days ago.\",\n"
         + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"pymkDestInvitationAcceptCount\",\n"
         + "      \"type\": \"int\",\n"
         + "      \"doc\": \"The number of accepted pymk invitations received by a dest member since 56 days ahead of 60 days ago.\",\n"
         + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"publicContributor\",\n"
         + "      \"type\": \"int\",\n"
         + "      \"doc\": \"The member has like/commented/shared or created content that has viral action\",\n"
         + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"privateContributor\",\n"
         + "      \"type\": \"int\",\n"
         + "      \"doc\": \"The member has contributed through private messaging or inMail\",\n"
         + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"totalActiveConnections\",\n"
         + "      \"type\": \"int\",\n"
         + "      \"doc\": \"The number of connections of a member who have made at least 1 contribution (like/comment/share/message) in the past 28 days\",\n"
         + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"privateActiveConnections\",\n"
         + "      \"type\": \"int\",\n"
         + "      \"doc\": \"The number of connections of a member who have made at least 1 private contribution (message/inMail) in the past 28 days\",\n"
         + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"publicActiveConnections\",\n"
         + "      \"type\": \"int\",\n"
         + "      \"doc\": \"The number of connections of a member who have made at least 1 public contribution (like/comment/share/publish) in the past 28 days\",\n"
         + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"allContributionCount\",\n"
         + "      \"type\": \"int\",\n"
         + "      \"doc\": \"The total number of contributions (likes, comments, shares, private messages/inmails) that the member contributed in the past 28 days\",\n"
         + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"likeCount\",\n"
         + "      \"type\": \"int\",\n"
         + "      \"doc\": \"The number of likes that the member contributed in the past 28 days\",\n"
         + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"commentCount\",\n"
         + "      \"type\": \"int\",\n"
         + "      \"doc\": \"The number of comments that the member contributed in the past 28 days\",\n"
         + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"shareCount\",\n"
         + "      \"type\": \"int\",\n"
         + "      \"doc\": \"The number of shares that the member contributed in the past 28 days\",\n"
         + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"articleContribCount\",\n"
         + "      \"type\": \"int\",\n"
         + "      \"doc\": \"The total number of articles that a member has contributed\",\n" + "      \"default\": 0\n"
         + "    },\n" + "    {\n" + "      \"name\": \"privateContribCount\",\n" + "      \"type\": \"int\",\n"
         + "      \"doc\": \"The number of private messages or inMails that the member has sent in the past 28 days\",\n"
         + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"allFeedContribCount\",\n"
         + "      \"type\": \"int\",\n"
         + "      \"doc\": \"The total number of contributions(likes, comments, shares) in Feed that the member contributed in the past 28 days\",\n"
         + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"feedLikeCount\",\n"
         + "      \"type\": \"int\",\n"
         + "      \"doc\": \"The total number of likes that the member contributed in Feed in the past 28 days\",\n"
         + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"feedCommentCount\",\n"
         + "      \"type\": \"int\",\n"
         + "      \"doc\": \"The total number of comments that the member contributed in Feed in the past 28 days\",\n"
         + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"feedShareCount\",\n"
         + "      \"type\": \"int\",\n"
         + "      \"doc\": \"The total number of shares that the member contributed in Feed in the past 28 days\",\n"
         + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"boostFactorConsumerOptimus\",\n"
         + "      \"type\": \"float\",\n"
         + "      \"doc\": \"Boost factor to be applied to all destinations -- optimus consumer-side experiment\",\n"
         + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"utilityConsumerOptimus\",\n"
         + "      \"type\": \"float\",\n"
         + "      \"doc\": \"Utility score for being destination -- optimus consumer-side experiment\",\n"
         + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"skillsEmbedding\",\n"
         + "      \"type\": {\n" + "        \"type\": \"array\",\n" + "        \"items\": \"float\"\n" + "      },\n"
         + "      \"doc\": \"The member skills embedding\",\n" + "      \"default\": []\n" + "    },\n" + "    {\n"
         + "      \"name\": \"titlesEmbedding\",\n" + "      \"type\": {\n" + "        \"type\": \"array\",\n"
         + "        \"items\": \"float\"\n" + "      },\n" + "      \"doc\": \"The member titles embedding\",\n"
         + "      \"default\": []\n" + "    },\n" + "    {\n" + "      \"name\": \"companiesEmbedding\",\n"
         + "      \"type\": {\n" + "        \"type\": \"array\",\n" + "        \"items\": \"float\"\n" + "      },\n"
         + "      \"doc\": \"The member companies embedding\",\n" + "      \"default\": []\n" + "    },\n" + "    {\n"
         + "      \"name\": \"schoolsEmbedding\",\n" + "      \"type\": {\n" + "        \"type\": \"array\",\n"
         + "        \"items\": \"float\"\n" + "      },\n" + "      \"doc\": \"The member schools embedding\",\n"
         + "      \"default\": []\n" + "    },\n" + "    {\n" + "      \"name\": \"needleEmbedding\",\n"
         + "      \"type\": {\n" + "        \"type\": \"array\",\n" + "        \"items\": \"float\"\n" + "      },\n"
         + "      \"doc\": \"The member needle embedding\",\n" + "      \"default\": []\n" + "    },\n" + "    {\n"
         + "      \"name\": \"needleEmbeddingA\",\n" + "      \"type\": {\n" + "        \"type\": \"array\",\n"
         + "        \"items\": \"float\"\n" + "      },\n"
         + "      \"doc\": \"The experimental needle embedding A,  which is reserved for fast model iteration\",\n"
         + "      \"default\": []\n" + "    },\n" + "    {\n" + "      \"name\": \"needleEmbeddingB\",\n"
         + "      \"type\": {\n" + "        \"type\": \"array\",\n" + "        \"items\": \"float\"\n" + "      },\n"
         + "      \"doc\": \"The experimental needle embedding B,  which is reserved for fast model iteration\",\n"
         + "      \"default\": []\n" + "    },\n" + "    {\n"
         + "      \"name\": \"deepCCXFeedScoringSourceEmbeddingV2_2\",\n" + "      \"type\": {\n"
         + "        \"type\": \"array\",\n" + "        \"items\": \"float\"\n" + "      },\n"
         + "      \"doc\": \"souce side embedding from deep-CCX based on feed metapath features\",\n"
         + "      \"default\": []\n" + "    },\n" + "    {\n"
         + "      \"name\": \"deepCCXFeedScoringDestEmbeddingV2_2\",\n" + "      \"type\": {\n"
         + "        \"type\": \"array\",\n" + "        \"items\": \"float\"\n" + "      },\n"
         + "      \"doc\": \"dest side embedding from deep-CCX based on feed metapath features\",\n"
         + "      \"default\": []\n" + "    },\n" + "    {\n"
         + "      \"name\": \"deepCCXEVScoringSourceEmbeddingV3_0\",\n" + "      \"type\": {\n"
         + "        \"type\": \"array\",\n" + "        \"items\": \"float\"\n" + "      },\n"
         + "      \"doc\": \"source side embedding from deep-CCX based on EV metapath features\",\n"
         + "      \"default\": []\n" + "    },\n" + "    {\n"
         + "      \"name\": \"deepCCXEVScoringDestEmbeddingV3_0\",\n" + "      \"type\": {\n"
         + "        \"type\": \"array\",\n" + "        \"items\": \"float\"\n" + "      },\n"
         + "      \"doc\": \"dest side embedding from deep-CCX based on EV metapath features\",\n"
         + "      \"default\": []\n" + "    },\n" + "    {\n" + "      \"name\": \"rlActionV0\",\n"
         + "      \"type\": {\n" + "        \"type\": \"array\",\n" + "        \"items\": \"float\"\n" + "      },\n"
         + "      \"doc\": \"The viewer action vector based on reinforcement learning (v0)\",\n"
         + "      \"default\": []\n" + "    },\n" + "    {\n" + "      \"name\": \"rlActionV1\",\n"
         + "      \"type\": {\n" + "        \"type\": \"array\",\n" + "        \"items\": \"float\"\n" + "      },\n"
         + "      \"doc\": \"The viewer action vector based on reinforcement learning (v1)\",\n"
         + "      \"default\": []\n" + "    },\n" + "    {\n" + "      \"name\": \"profileCompanies\",\n"
         + "      \"type\": {\n" + "        \"type\": \"array\",\n" + "        \"items\": {\n"
         + "          \"type\": \"record\",\n" + "          \"name\": \"profileCompanies\",\n"
         + "          \"fields\": [\n" + "            {\n" + "              \"name\": \"companyId\",\n"
         + "              \"type\": \"int\",\n" + "              \"doc\": \"\",\n" + "              \"default\": 0\n"
         + "            },\n" + "            {\n" + "              \"name\": \"industryId\",\n"
         + "              \"type\": \"int\",\n" + "              \"doc\": \"\",\n" + "              \"default\": 0\n"
         + "            },\n" + "            {\n" + "              \"name\": \"isCurrent\",\n"
         + "              \"type\": \"boolean\",\n" + "              \"doc\": \"\",\n"
         + "              \"default\": false\n" + "            },\n" + "            {\n"
         + "              \"name\": \"position\",\n" + "              \"type\": {\n"
         + "                \"type\": \"string\",\n" + "                \"avro.java.string\": \"String\"\n"
         + "              },\n" + "              \"doc\": \"\",\n" + "              \"default\": \"\"\n"
         + "            }\n" + "          ]\n" + "        }\n" + "      },\n"
         + "      \"doc\": \"Profile company info\",\n" + "      \"default\": []\n" + "    },\n" + "    {\n"
         + "      \"name\": \"profileSchools\",\n" + "      \"type\": {\n" + "        \"type\": \"array\",\n"
         + "        \"items\": {\n" + "          \"type\": \"record\",\n" + "          \"name\": \"profileSchools\",\n"
         + "          \"fields\": [\n" + "            {\n" + "              \"name\": \"schoolId\",\n"
         + "              \"type\": \"int\",\n" + "              \"doc\": \"deprecated\",\n"
         + "              \"default\": 0\n" + "            },\n" + "            {\n"
         + "              \"name\": \"organizationId\",\n" + "              \"type\": \"long\",\n"
         + "              \"doc\": \"\",\n" + "              \"default\": 0\n" + "            },\n" + "            {\n"
         + "              \"name\": \"cipCodeId\",\n" + "              \"type\": {\n"
         + "                \"type\": \"string\",\n" + "                \"avro.java.string\": \"String\"\n"
         + "              },\n" + "              \"doc\": \"\",\n" + "              \"default\": \"\"\n"
         + "            },\n" + "            {\n" + "              \"name\": \"degreeId\",\n"
         + "              \"type\": \"int\",\n" + "              \"doc\": \"\",\n" + "              \"default\": 0\n"
         + "            },\n" + "            {\n" + "              \"name\": \"startTime\",\n"
         + "              \"type\": \"long\",\n" + "              \"doc\": \"\",\n" + "              \"default\": -1\n"
         + "            }\n" + "          ]\n" + "        }\n" + "      },\n"
         + "      \"doc\": \"Profile school info\",\n" + "      \"default\": []\n" + "    },\n" + "    {\n"
         + "      \"name\": \"profileGeo\",\n" + "      \"type\": {\n" + "        \"type\": \"string\",\n"
         + "        \"avro.java.string\": \"String\"\n" + "      },\n" + "      \"doc\": \"Profile geo\",\n"
         + "      \"default\": \"\"\n" + "    },\n" + "    {\n" + "      \"name\": \"memberLanguages\",\n"
         + "      \"type\": {\n" + "        \"type\": \"array\",\n" + "        \"items\": {\n"
         + "          \"type\": \"string\",\n" + "          \"avro.java.string\": \"String\"\n" + "        }\n"
         + "      },\n" + "      \"doc\": \"Inferred languages over a threshold for a member.\",\n"
         + "      \"default\": []\n" + "    },\n" + "    {\n" + "      \"name\": \"profileRegion\",\n"
         + "      \"type\": \"long\",\n"
         + "      \"doc\": \"Profile region, using the MARKET_AREA of bing geo, corresponding to the former region code.\",\n"
         + "      \"default\": -1\n" + "    },\n" + "    {\n" + "      \"name\": \"profileOccupationId\",\n"
         + "      \"type\": \"int\",\n"
         + "      \"doc\": \"The standardized supertitle id with the highest confidence score from the most recent position of the user. The name occupation id is aligned with that in om_segment.\",\n"
         + "      \"default\": -1\n" + "    },\n" + "    {\n" + "      \"name\": \"latitude\",\n"
         + "      \"type\": \"float\",\n" + "      \"doc\": \"The latitude fetched by the first geo entity\",\n"
         + "      \"default\": 200\n" + "    },\n" + "    {\n" + "      \"name\": \"longitude\",\n"
         + "      \"type\": \"float\",\n" + "      \"doc\": \"The longitude fetched by the first geo entity\",\n"
         + "      \"default\": 200\n" + "    },\n" + "    {\n" + "      \"name\": \"deltaPcreate\",\n"
         + "      \"type\": \"float\",\n"
         + "      \"doc\": \"Member feedback sensitivity (for creation) -- value is between 0 and 1.\",\n"
         + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"followsAsCTA\",\n"
         + "      \"type\": \"boolean\",\n" + "      \"doc\": \"Member who sets follows as CTA\",\n"
         + "      \"default\": false\n" + "    },\n" + "    {\n"
         + "      \"name\": \"blockUnwantedInvitesOrReconnectInvites\",\n" + "      \"type\": \"boolean\",\n"
         + "      \"doc\": \"This setting is true for a Member who allows connection request from people who know the members email or appear in the members imported contact list.\",\n"
         + "      \"default\": false\n" + "    },\n" + "    {\n" + "      \"name\": \"isInternationallyOriented\",\n"
         + "      \"type\": \"boolean\",\n"
         + "      \"doc\": \"If a member is internationally oriented, as defined in go/intloriented\",\n"
         + "      \"default\": false\n" + "    },\n" + "    {\n" + "      \"name\": \"memberGroups\",\n"
         + "      \"type\": {\n" + "        \"type\": \"array\",\n" + "        \"items\": \"long\"\n" + "      },\n"
         + "      \"doc\": \"A list of healthy groups ids (go/healthyGroups) which the member is part of.\",\n"
         + "      \"default\": []\n" + "    },\n" + "    {\n" + "      \"name\": \"organizationsFollowed\",\n"
         + "      \"type\": {\n" + "        \"type\": \"array\",\n" + "        \"items\": \"long\"\n" + "      },\n"
         + "      \"doc\": \"Organizations followed by the member, such as schools and companies.\",\n"
         + "      \"default\": []\n" + "    },\n" + "    {\n" + "      \"name\": \"srcMemberFilters\",\n"
         + "      \"type\": \"long\",\n"
         + "      \"doc\": \"If a member is in the pymk offline source member filters, it will be 1, otherwise it will be 0\",\n"
         + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"destMemberFilters\",\n"
         + "      \"type\": \"long\",\n"
         + "      \"doc\": \"If a member is in the pymk offline dest member filters, it will be 1, otherwise it will be 0\",\n"
         + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"mlc\",\n" + "      \"type\": {\n"
         + "        \"type\": \"string\",\n" + "        \"avro.java.string\": \"String\"\n" + "      },\n"
         + "      \"doc\": \"Member Life Cycle V3 assignment for this member\",\n" + "      \"default\": \"\"\n"
         + "    },\n" + "    {\n" + "      \"name\": \"lastActiveTime\",\n" + "      \"type\": \"long\",\n"
         + "      \"doc\": \"Epoch time in milliseconds of the last time the member was active on LinkedIn\",\n"
         + "      \"default\": 0\n" + "    },\n" + "    {\n"
         + "      \"name\": \"careerInterestSurveyResponseActive\",\n" + "      \"type\": \"float\",\n"
         + "      \"doc\": \"Whether activity-inferred career interest survey response is active. More info: https://iwww.corp.linkedin.com/wiki/cf/display/ENGS/Member+Intent\",\n"
         + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"hiringManagerIntent\",\n"
         + "      \"type\": \"float\",\n"
         + "      \"doc\": \"Whether member has intent to hire. Talent professionals excluded. More info: https://iwww.corp.linkedin.com/wiki/cf/display/ENGS/Member+Intent\",\n"
         + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"contentContributionIntent\",\n"
         + "      \"type\": \"float\",\n"
         + "      \"doc\": \"Intent to feed content post and share. More info: https://iwww.corp.linkedin.com/wiki/cf/display/ENGS/Member+Intent\",\n"
         + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"contentConsumerIntent\",\n"
         + "      \"type\": \"float\",\n"
         + "      \"doc\": \"Intent to article read and video play(non-auto), More info: https://iwww.corp.linkedin.com/wiki/cf/display/ENGS/Member+Intent\",\n"
         + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"personalizedMoopConnectCoeff\",\n"
         + "      \"type\": \"float\",\n"
         + "      \"doc\": \"Coefficients calculated from the personalized multi-objective optimization: more info at go/pMoo.\",\n"
         + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"pMooVersions\",\n"
         + "      \"type\": {\n" + "        \"type\": \"array\",\n" + "        \"items\": {\n"
         + "          \"type\": \"string\",\n" + "          \"avro.java.string\": \"String\"\n" + "        }\n"
         + "      },\n" + "      \"doc\": \"pMoo version IDs\",\n" + "      \"default\": []\n" + "    },\n" + "    {\n"
         + "      \"name\": \"pMooCoefficientIds\",\n" + "      \"type\": {\n" + "        \"type\": \"array\",\n"
         + "        \"items\": {\n" + "          \"type\": \"string\",\n"
         + "          \"avro.java.string\": \"String\"\n" + "        }\n" + "      },\n"
         + "      \"doc\": \"terms for different FPR combinations in pMoo\",\n" + "      \"default\": []\n" + "    },\n"
         + "    {\n" + "      \"name\": \"pMooCoefficientValues\",\n" + "      \"type\": {\n"
         + "        \"type\": \"array\",\n" + "        \"items\": \"float\"\n" + "      },\n"
         + "      \"doc\": \"pMoo coefficient values\",\n" + "      \"default\": []\n" + "    },\n" + "    {\n"
         + "      \"name\": \"gender\",\n" + "      \"type\": {\n" + "        \"type\": \"string\",\n"
         + "        \"avro.java.string\": \"String\"\n" + "      },\n"
         + "      \"doc\": \"Gender of member ['MALE','FEMALE', 'NON-BINARY','UNKNOWN'...]\",\n"
         + "      \"default\": \"\"\n" + "    },\n" + "    {\n" + "      \"name\": \"yearsFromFirstEduEnd\",\n"
         + "      \"type\": \"int\",\n"
         + "      \"doc\": \"Number of years from the member's earliest education end time to today\",\n"
         + "      \"default\": -21\n" + "    },\n" + "    {\n" + "      \"name\": \"srcMemberFilterReasons\",\n"
         + "      \"type\": {\n" + "        \"type\": \"array\",\n" + "        \"items\": \"int\"\n" + "      },\n"
         + "      \"doc\": \"Aggregated list of source member filter reason. Using int because Avro Enums are not evolvable. The original enum value is defined in pymk-member-filters MemberFilterReason.java. Example mapping includes but not limited to: 0 => BLACK_LIST, 1 => CELEBS, 2 => CLOSED\",\n"
         + "      \"default\": []\n" + "    },\n" + "    {\n" + "      \"name\": \"destMemberFilterReasons\",\n"
         + "      \"type\": {\n" + "        \"type\": \"array\",\n" + "        \"items\": \"int\"\n" + "      },\n"
         + "      \"doc\": \"Aggregated list of destination member filter reason. Using int because Avro Enums are not evolvable. The original enum value is defined in pymk-member-filters MemberFilterReason.java. Example mapping includes but not limited to: 0 => BLACK_LIST, 1 => CELEBS, 2 => CLOSED\",\n"
         + "      \"default\": []\n" + "    },\n" + "    {\n" + "      \"name\": \"memberCareerTransitionEmbedding\",\n"
         + "      \"type\": {\n" + "        \"type\": \"array\",\n" + "        \"items\": \"float\"\n" + "      },\n"
         + "      \"doc\": \"Member career transition embedding\",\n" + "      \"default\": []\n" + "    },\n"
         + "    {\n" + "      \"name\": \"memberSpecialties\",\n" + "      \"type\": {\n"
         + "        \"type\": \"array\",\n" + "        \"items\": \"float\"\n" + "      },\n"
         + "      \"doc\": \"Member specialty embedding. The top member specialties are stored, with the specialtyID extracted. Each member has fewer than 5 specialties. More details can be found in go/specialty\",\n"
         + "      \"default\": []\n" + "    }\n" + "  ]\n" + "}";

    String valueSchemaStr2 = "{\n" + "  \"type\": \"record\",\n" + "  \"name\": \"memberFeaturesObject\",\n"
        + "  \"namespace\": \"com.linkedin.pymk.schema\",\n" + "  \"fields\": [\n" + "    {\n"
        + "      \"name\": \"visitProbabilityForInvite\",\n" + "      \"type\": \"float\",\n"
        + "      \"doc\": \"The probability of a member visiting the site after sending this member an invitation. The range of this value will between 0 to 1. The higher the value, the more likely that member will visit the site. \",\n"
        + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"activityLevel\",\n"
        + "      \"type\": \"int\",\n"
        + "      \"doc\": \"Member activity level, from 0-4. 0-4 means: 0(Onboarding), 1(Dormant), 2(OneByOne), 3(OneByThree), 4(FourbyFour)\",\n"
        + "      \"default\": -1\n" + "    },\n" + "    {\n" + "      \"name\": \"connectionCount\",\n"
        + "      \"type\": \"int\",\n" + "      \"doc\": \"The total connection count of a member.\",\n"
        + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"lastConnectionAcceptedAt\",\n"
        + "      \"type\": \"int\",\n"
        + "      \"doc\": \"The Unix timestamp (seconds) of the most recently accepted connection.\",\n"
        + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"pVisitModel\",\n"
        + "      \"type\": {\n" + "        \"type\": \"string\",\n" + "        \"avro.java.string\": \"String\"\n"
        + "      },\n" + "      \"doc\": \"Different lix treatment(pvisit models) for computing pvisit score.\",\n"
        + "      \"default\": \"\"\n" + "    },\n" + "    {\n" + "      \"name\": \"pVisitBasicModelScore\",\n"
        + "      \"type\": \"float\",\n"
        + "      \"doc\": \"The score is computed based on the pVisit basic model which is simply member visit probability.\",\n"
        + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"pVisitEqmGainModelScore\",\n"
        + "      \"type\": \"float\",\n"
        + "      \"doc\": \"The pvisit score is computed based on a model that uses potential eQM gain as weight during model training. eQM_gain model slightly prefer member visit from who has more eQM gain.\",\n"
        + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"invReceivedCount\",\n"
        + "      \"type\": \"int\",\n"
        + "      \"doc\": \"The number of member connection invitations received by the member in the past 7 days.\",\n"
        + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"publicContributor\",\n"
        + "      \"type\": \"int\",\n"
        + "      \"doc\": \"The member has like/commented/shared or created content that has viral action\",\n"
        + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"privateContributor\",\n"
        + "      \"type\": \"int\",\n"
        + "      \"doc\": \"The member has contributed through private messaging or inMail\",\n"
        + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"totalActiveConnections\",\n"
        + "      \"type\": \"int\",\n"
        + "      \"doc\": \"The number of connections of a member who have made at least 1 contribution (like/comment/share/message) in the past 7 days\",\n"
        + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"privateActiveConnections\",\n"
        + "      \"type\": \"int\",\n"
        + "      \"doc\": \"The number of connections of a member who have made at least 1 private contribution (message/inMail) in the past 7 days\",\n"
        + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"publicActiveConnections\",\n"
        + "      \"type\": \"int\",\n"
        + "      \"doc\": \"The number of connections of a member who have made at least 1 public contribution (like/comment/share/publish) in the past 7 days\",\n"
        + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"allContributionCount\",\n"
        + "      \"type\": \"int\",\n"
        + "      \"doc\": \"The total number of contributions (likes, comments, shares, private messages/inmails) that the member contributed in the past 7 days\",\n"
        + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"likeCount\",\n"
        + "      \"type\": \"int\",\n"
        + "      \"doc\": \"The number of likes that the member contributed in the past 7 days\",\n"
        + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"commentCount\",\n"
        + "      \"type\": \"int\",\n"
        + "      \"doc\": \"The number of comments that the member contributed in the past 7 days\",\n"
        + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"shareCount\",\n"
        + "      \"type\": \"int\",\n"
        + "      \"doc\": \"The number of shares that the member contributed in the past 7 days\",\n"
        + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"articleContribCount\",\n"
        + "      \"type\": \"int\",\n"
        + "      \"doc\": \"The total number of articles that a member has contributed\",\n" + "      \"default\": 0\n"
        + "    },\n" + "    {\n" + "      \"name\": \"privateContribCount\",\n" + "      \"type\": \"int\",\n"
        + "      \"doc\": \"The number of private messages or inMails that the member has sent in the past 7 days\",\n"
        + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"allFeedContribCount\",\n"
        + "      \"type\": \"int\",\n"
        + "      \"doc\": \"The total number of contributions(likes, comments, shares) in Feed that the member contributed in the past 7 days\",\n"
        + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"feedLikeCount\",\n"
        + "      \"type\": \"int\",\n"
        + "      \"doc\": \"The total number of likes that the member contributed in Feed in the past 7 days\",\n"
        + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"feedCommentCount\",\n"
        + "      \"type\": \"int\",\n"
        + "      \"doc\": \"The total number of comments that the member contributed in Feed in the past 7 days\",\n"
        + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"feedShareCount\",\n"
        + "      \"type\": \"int\",\n"
        + "      \"doc\": \"The total number of shares that the member contributed in Feed in the past 7 days\",\n"
        + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"boostFactorConsumerOptimus\",\n"
        + "      \"type\": \"float\",\n"
        + "      \"doc\": \"Boost factor to be applied to all destinations -- optimus consumer-side experiment\",\n"
        + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"utilityConsumerOptimus\",\n"
        + "      \"type\": \"float\",\n"
        + "      \"doc\": \"Utility score for being destination -- optimus consumer-side experiment\",\n"
        + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"skillsEmbedding\",\n"
        + "      \"type\": {\n" + "        \"type\": \"array\",\n" + "        \"items\": \"float\"\n" + "      },\n"
        + "      \"doc\": \"The member skills embedding\",\n" + "      \"default\": []\n" + "    },\n" + "    {\n"
        + "      \"name\": \"titlesEmbedding\",\n" + "      \"type\": {\n" + "        \"type\": \"array\",\n"
        + "        \"items\": \"float\"\n" + "      },\n" + "      \"doc\": \"The member titles embedding\",\n"
        + "      \"default\": []\n" + "    },\n" + "    {\n" + "      \"name\": \"companiesEmbedding\",\n"
        + "      \"type\": {\n" + "        \"type\": \"array\",\n" + "        \"items\": \"float\"\n" + "      },\n"
        + "      \"doc\": \"The member companies embedding\",\n" + "      \"default\": []\n" + "    },\n" + "    {\n"
        + "      \"name\": \"schoolsEmbedding\",\n" + "      \"type\": {\n" + "        \"type\": \"array\",\n"
        + "        \"items\": \"float\"\n" + "      },\n" + "      \"doc\": \"The member schools embedding\",\n"
        + "      \"default\": []\n" + "    },\n" + "    {\n" + "      \"name\": \"needleEmbedding\",\n"
        + "      \"type\": {\n" + "        \"type\": \"array\",\n" + "        \"items\": \"float\"\n" + "      },\n"
        + "      \"doc\": \"The member needle embedding\",\n" + "      \"default\": []\n" + "    },\n" + "    {\n"
        + "      \"name\": \"needleEmbeddingA\",\n" + "      \"type\": {\n" + "        \"type\": \"array\",\n"
        + "        \"items\": \"float\"\n" + "      },\n"
        + "      \"doc\": \"The experimental needle embedding A,  which is reserved for fast model iteration\",\n"
        + "      \"default\": []\n" + "    },\n" + "    {\n" + "      \"name\": \"needleEmbeddingB\",\n"
        + "      \"type\": {\n" + "        \"type\": \"array\",\n" + "        \"items\": \"float\"\n" + "      },\n"
        + "      \"doc\": \"The experimental needle embedding B,  which is reserved for fast model iteration\",\n"
        + "      \"default\": []\n" + "    },\n" + "    {\n" + "      \"name\": \"pymkSrcCosineV0\",\n"
        + "      \"type\": {\n" + "        \"type\": \"array\",\n" + "        \"items\": \"float\"\n" + "      },\n"
        + "      \"doc\": \"The src member pymk embedding for cosine similarity interaction\",\n"
        + "      \"default\": []\n" + "    },\n" + "    {\n" + "      \"name\": \"pymkDestCosineV0\",\n"
        + "      \"type\": {\n" + "        \"type\": \"array\",\n" + "        \"items\": \"float\"\n" + "      },\n"
        + "      \"doc\": \"The dest member pymk embedding for cosine similarity interaction\",\n"
        + "      \"default\": []\n" + "    },\n" + "    {\n" + "      \"name\": \"cohortSrcCosineV0\",\n"
        + "      \"type\": {\n" + "        \"type\": \"array\",\n" + "        \"items\": \"float\"\n" + "      },\n"
        + "      \"doc\": \"The dest member cohort embedding V0 for cosine similarity interaction. V0 uses only cohort mvp features.\",\n"
        + "      \"default\": []\n" + "    },\n" + "    {\n" + "      \"name\": \"cohortDestCosineV0\",\n"
        + "      \"type\": {\n" + "        \"type\": \"array\",\n" + "        \"items\": \"float\"\n" + "      },\n"
        + "      \"doc\": \"The dest member cohort embedding V0 for cosine similarity interaction. V0 uses only cohort mvp features.\",\n"
        + "      \"default\": []\n" + "    },\n" + "    {\n" + "      \"name\": \"cohortSrcCosineV1\",\n"
        + "      \"type\": {\n" + "        \"type\": \"array\",\n" + "        \"items\": \"float\"\n" + "      },\n"
        + "      \"doc\": \"The src member cohort embedding V1 for cosine similarity interaction. V1 uses cohort mvp+transformed features\",\n"
        + "      \"default\": []\n" + "    },\n" + "    {\n" + "      \"name\": \"cohortDestCosineV1\",\n"
        + "      \"type\": {\n" + "        \"type\": \"array\",\n" + "        \"items\": \"float\"\n" + "      },\n"
        + "      \"doc\": \"The src member cohort embedding V1 for cosine similarity interaction. V1 uses cohort mvp+transformed features\",\n"
        + "      \"default\": []\n" + "    },\n" + "    {\n" + "      \"name\": \"cohortSrcCosineV2\",\n"
        + "      \"type\": {\n" + "        \"type\": \"array\",\n" + "        \"items\": \"float\"\n" + "      },\n"
        + "      \"doc\": \"The src member cohort embedding V2 for cosine similarity interaction.\",\n"
        + "      \"default\": []\n" + "    },\n" + "    {\n" + "      \"name\": \"cohortDestCosineV2\",\n"
        + "      \"type\": {\n" + "        \"type\": \"array\",\n" + "        \"items\": \"float\"\n" + "      },\n"
        + "      \"doc\": \"The dest member cohort embedding V2 for cosine similarity interaction.\",\n"
        + "      \"default\": []\n" + "    },\n" + "    {\n" + "      \"name\": \"cohortSrcCosineV3\",\n"
        + "      \"type\": {\n" + "        \"type\": \"array\",\n" + "        \"items\": \"float\"\n" + "      },\n"
        + "      \"doc\": \"The src member cohort embedding V3 for cosine similarity interaction.\",\n"
        + "      \"default\": []\n" + "    },\n" + "    {\n" + "      \"name\": \"cohortDestCosineV3\",\n"
        + "      \"type\": {\n" + "        \"type\": \"array\",\n" + "        \"items\": \"float\"\n" + "      },\n"
        + "      \"doc\": \"The dest member cohort embedding V3 for cosine similarity interaction.\",\n"
        + "      \"default\": []\n" + "    },\n" + "    {\n" + "      \"name\": \"cohortSrcHadamardV4\",\n"
        + "      \"type\": {\n" + "        \"type\": \"array\",\n" + "        \"items\": \"float\"\n" + "      },\n"
        + "      \"doc\": \"The src member cohort embedding embedding V4 for hadamard interaction.\",\n"
        + "      \"default\": []\n" + "    },\n" + "    {\n" + "      \"name\": \"cohortDestHadamardV4\",\n"
        + "      \"type\": {\n" + "        \"type\": \"array\",\n" + "        \"items\": \"float\"\n" + "      },\n"
        + "      \"doc\": \"The dest member cohort embedding embedding V4 for hadamard interaction.\",\n"
        + "      \"default\": []\n" + "    },\n" + "    {\n" + "      \"name\": \"cohortSrcHadamardV5\",\n"
        + "      \"type\": {\n" + "        \"type\": \"array\",\n" + "        \"items\": \"float\"\n" + "      },\n"
        + "      \"doc\": \"The src member cohort embedding embedding V5 for hadamard interaction.\",\n"
        + "      \"default\": []\n" + "    },\n" + "    {\n" + "      \"name\": \"cohortDestHadamardV5\",\n"
        + "      \"type\": {\n" + "        \"type\": \"array\",\n" + "        \"items\": \"float\"\n" + "      },\n"
        + "      \"doc\": \"The dest member cohort embedding embedding V5 for hadamard interaction.\",\n"
        + "      \"default\": []\n" + "    },\n" + "    {\n" + "      \"name\": \"rlActionV0\",\n"
        + "      \"type\": {\n" + "        \"type\": \"array\",\n" + "        \"items\": \"float\"\n" + "      },\n"
        + "      \"doc\": \"The viewer action vector based on reinforcement learning (v0)\",\n"
        + "      \"default\": []\n" + "    },\n" + "    {\n" + "      \"name\": \"rlActionV1\",\n"
        + "      \"type\": {\n" + "        \"type\": \"array\",\n" + "        \"items\": \"float\"\n" + "      },\n"
        + "      \"doc\": \"The viewer action vector based on reinforcement learning (v1)\",\n"
        + "      \"default\": []\n" + "    },\n" + "    {\n" + "      \"name\": \"cohortSrcHadamardV6\",\n"
        + "      \"type\": {\n" + "        \"type\": \"array\",\n" + "        \"items\": \"float\"\n" + "      },\n"
        + "      \"doc\": \"The src member cohort embedding embedding V6 for hadamard product interaction.\",\n"
        + "      \"default\": []\n" + "    },\n" + "    {\n" + "      \"name\": \"cohortDestHadamardV6\",\n"
        + "      \"type\": {\n" + "        \"type\": \"array\",\n" + "        \"items\": \"float\"\n" + "      },\n"
        + "      \"doc\": \"The dest member cohort embedding embedding V6 for hadamard product interaction.\",\n"
        + "      \"default\": []\n" + "    },\n" + "    {\n" + "      \"name\": \"cohortSrcCosineV7\",\n"
        + "      \"type\": {\n" + "        \"type\": \"array\",\n" + "        \"items\": \"float\"\n" + "      },\n"
        + "      \"doc\": \"The src member cohort embedding embedding V7 for cosine similarity interaction.\",\n"
        + "      \"default\": []\n" + "    },\n" + "    {\n" + "      \"name\": \"cohortDestCosineV7\",\n"
        + "      \"type\": {\n" + "        \"type\": \"array\",\n" + "        \"items\": \"float\"\n" + "      },\n"
        + "      \"doc\": \"The dest member cohort embedding embedding V7 for cosine similarity interaction.\",\n"
        + "      \"default\": []\n" + "    },\n" + "    {\n" + "      \"name\": \"cohortSrcCosineV8\",\n"
        + "      \"type\": {\n" + "        \"type\": \"array\",\n" + "        \"items\": \"float\"\n" + "      },\n"
        + "      \"doc\": \"The src member cohort embedding embedding V8 for cosine similarity interaction.\",\n"
        + "      \"default\": []\n" + "    },\n" + "    {\n" + "      \"name\": \"cohortDestCosineV8\",\n"
        + "      \"type\": {\n" + "        \"type\": \"array\",\n" + "        \"items\": \"float\"\n" + "      },\n"
        + "      \"doc\": \"The dest member cohort embedding embedding V8 for cosine similarity interaction.\",\n"
        + "      \"default\": []\n" + "    },\n" + "    {\n" + "      \"name\": \"profileCompanies\",\n"
        + "      \"type\": {\n" + "        \"type\": \"array\",\n" + "        \"items\": {\n"
        + "          \"type\": \"record\",\n" + "          \"name\": \"profileCompanies\",\n"
        + "          \"fields\": [\n" + "            {\n" + "              \"name\": \"companyId\",\n"
        + "              \"type\": \"int\",\n" + "              \"doc\": \"\",\n" + "              \"default\": 0\n"
        + "            },\n" + "            {\n" + "              \"name\": \"industryId\",\n"
        + "              \"type\": \"int\",\n" + "              \"doc\": \"\",\n" + "              \"default\": 0\n"
        + "            },\n" + "            {\n" + "              \"name\": \"isCurrent\",\n"
        + "              \"type\": \"boolean\",\n" + "              \"doc\": \"\",\n"
        + "              \"default\": false\n" + "            },\n" + "            {\n"
        + "              \"name\": \"position\",\n" + "              \"type\": {\n"
        + "                \"type\": \"string\",\n" + "                \"avro.java.string\": \"String\"\n"
        + "              },\n" + "              \"doc\": \"\",\n" + "              \"default\": \"\"\n"
        + "            }\n" + "          ]\n" + "        }\n" + "      },\n"
        + "      \"doc\": \"Profile company info\",\n" + "      \"default\": []\n" + "    },\n" + "    {\n"
        + "      \"name\": \"profileSchools\",\n" + "      \"type\": {\n" + "        \"type\": \"array\",\n"
        + "        \"items\": {\n" + "          \"type\": \"record\",\n" + "          \"name\": \"profileSchools\",\n"
        + "          \"fields\": [\n" + "            {\n" + "              \"name\": \"schoolId\",\n"
        + "              \"type\": \"int\",\n" + "              \"doc\": \"\",\n" + "              \"default\": 0\n"
        + "            },\n" + "            {\n" + "              \"name\": \"cipCodeId\",\n"
        + "              \"type\": {\n" + "                \"type\": \"string\",\n"
        + "                \"avro.java.string\": \"String\"\n" + "              },\n" + "              \"doc\": \"\",\n"
        + "              \"default\": \"\"\n" + "            },\n" + "            {\n"
        + "              \"name\": \"degreeId\",\n" + "              \"type\": \"int\",\n"
        + "              \"doc\": \"\",\n" + "              \"default\": 0\n" + "            },\n" + "            {\n"
        + "              \"name\": \"startTime\",\n" + "              \"type\": \"long\",\n"
        + "              \"doc\": \"\",\n" + "              \"default\": -1\n" + "            },\n" + "            {\n"
        + "              \"name\": \"organizationId\",\n" + "              \"type\": \"long\",\n"
        + "              \"doc\": \"\",\n" + "              \"default\": 0\n" + "            }\n" + "          ]\n"
        + "        }\n" + "      },\n" + "      \"doc\": \"Profile school info\",\n" + "      \"default\": []\n"
        + "    },\n" + "    {\n" + "      \"name\": \"profileGeo\",\n" + "      \"type\": {\n"
        + "        \"type\": \"string\",\n" + "        \"avro.java.string\": \"String\"\n" + "      },\n"
        + "      \"doc\": \"Profile geo\",\n" + "      \"default\": \"\"\n" + "    },\n" + "    {\n"
        + "      \"name\": \"memberLanguages\",\n" + "      \"type\": {\n" + "        \"type\": \"array\",\n"
        + "        \"items\": {\n" + "          \"type\": \"string\",\n"
        + "          \"avro.java.string\": \"String\"\n" + "        }\n" + "      },\n"
        + "      \"doc\": \"Inferred languages over a threshold for a member.\",\n" + "      \"default\": []\n"
        + "    },\n" + "    {\n" + "      \"name\": \"profileRegion\",\n" + "      \"type\": \"long\",\n"
        + "      \"doc\": \"Profile region, using the MARKET_AREA of bing geo, corresponding to the former region code.\",\n"
        + "      \"default\": -1\n" + "    },\n" + "    {\n" + "      \"name\": \"profileOccupationId\",\n"
        + "      \"type\": \"int\",\n"
        + "      \"doc\": \"The standardized supertitle id with the highest confidence score from the most recent position of the user. The name occupation id is aligned with that in om_segment.\",\n"
        + "      \"default\": -1\n" + "    },\n" + "    {\n" + "      \"name\": \"deltaPcreate\",\n"
        + "      \"type\": \"float\",\n"
        + "      \"doc\": \"Member feedback sensitivity (for creation) -- value is between 0 and 1.\",\n"
        + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"followsAsCTA\",\n"
        + "      \"type\": \"boolean\",\n" + "      \"doc\": \"Member who sets follows as CTA\",\n"
        + "      \"default\": false\n" + "    },\n" + "    {\n"
        + "      \"name\": \"blockUnwantedInvitesOrReconnectInvites\",\n" + "      \"type\": \"boolean\",\n"
        + "      \"doc\": \"This setting is true for a Member who allows connection request from people who know the members email or appear in the members imported contact list.\",\n"
        + "      \"default\": false\n" + "    },\n" + "    {\n" + "      \"name\": \"isInternationallyOriented\",\n"
        + "      \"type\": \"boolean\",\n"
        + "      \"doc\": \"If a member is internationally oriented, as defined in go/intloriented\",\n"
        + "      \"default\": false\n" + "    },\n" + "    {\n" + "      \"name\": \"memberGroups\",\n"
        + "      \"type\": {\n" + "        \"type\": \"array\",\n" + "        \"items\": \"long\"\n" + "      },\n"
        + "      \"doc\": \"A list of healthy groups ids (go/healthyGroups) which the member is part of.\",\n"
        + "      \"default\": []\n" + "    },\n" + "    {\n" + "      \"name\": \"organizationsFollowed\",\n"
        + "      \"type\": {\n" + "        \"type\": \"array\",\n" + "        \"items\": \"long\"\n" + "      },\n"
        + "      \"doc\": \"Organizations followed by the member, such as schools and companies.\",\n"
        + "      \"default\": []\n" + "    },\n" + "    {\n" + "      \"name\": \"srcMemberFilters\",\n"
        + "      \"type\": \"long\",\n"
        + "      \"doc\": \"If a member is in the pymk offline source member filters, it will be 1, otherwise it will be 0\",\n"
        + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"destMemberFilters\",\n"
        + "      \"type\": \"long\",\n"
        + "      \"doc\": \"If a member is in the pymk offline dest member filters, it will be 1, otherwise it will be 0\",\n"
        + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"mlcV3\",\n" + "      \"type\": {\n"
        + "        \"type\": \"string\",\n" + "        \"avro.java.string\": \"String\"\n" + "      },\n"
        + "      \"doc\": \"Member Life Cycle V3 assignment for this member\",\n" + "      \"default\": \"\"\n"
        + "    },\n" + "    {\n" + "      \"name\": \"lastActiveTime\",\n" + "      \"type\": \"long\",\n"
        + "      \"doc\": \"Epoch time in milliseconds of the last time the member was active on LinkedIn\",\n"
        + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"mlc\",\n" + "      \"type\": {\n"
        + "        \"type\": \"string\",\n" + "        \"avro.java.string\": \"String\"\n" + "      },\n"
        + "      \"doc\": \"Member Life Cycle V3 assignment for this member\",\n" + "      \"default\": \"\"\n"
        + "    },\n" + "    {\n" + "      \"name\": \"cohortSrcCosineV9\",\n" + "      \"type\": {\n"
        + "        \"type\": \"array\",\n" + "        \"items\": \"float\"\n" + "      },\n"
        + "      \"doc\": \"The src member cohort embedding V9 for cosine similarity interaction.\",\n"
        + "      \"default\": []\n" + "    },\n" + "    {\n" + "      \"name\": \"cohortDestCosineV9\",\n"
        + "      \"type\": {\n" + "        \"type\": \"array\",\n" + "        \"items\": \"float\"\n" + "      },\n"
        + "      \"doc\": \"The dest member cohort embedding V9 for cosine similarity interaction.\",\n"
        + "      \"default\": []\n" + "    },\n" + "    {\n"
        + "      \"name\": \"careerInterestSurveyResponseActive\",\n" + "      \"type\": \"float\",\n"
        + "      \"doc\": \"Whether activity-inferred career interest survey response is active. More info: https://iwww.corp.linkedin.com/wiki/cf/display/ENGS/Member+Intent\",\n"
        + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"hiringManagerIntent\",\n"
        + "      \"type\": \"float\",\n"
        + "      \"doc\": \"Whether member has intent to hire. Talent professionals excluded. More info: https://iwww.corp.linkedin.com/wiki/cf/display/ENGS/Member+Intent\",\n"
        + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"contentContributionIntent\",\n"
        + "      \"type\": \"float\",\n"
        + "      \"doc\": \"Intent to feed content post and share. More info: https://iwww.corp.linkedin.com/wiki/cf/display/ENGS/Member+Intent\",\n"
        + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"contentConsumerIntent\",\n"
        + "      \"type\": \"float\",\n"
        + "      \"doc\": \"Intent to article read and video play(non-auto), More info: https://iwww.corp.linkedin.com/wiki/cf/display/ENGS/Member+Intent\",\n"
        + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"cohortSrcCosineV10\",\n"
        + "      \"type\": {\n" + "        \"type\": \"array\",\n" + "        \"items\": \"float\"\n" + "      },\n"
        + "      \"doc\": \"The src member cohort embedding V10 for cosine similarity interaction.\",\n"
        + "      \"default\": []\n" + "    },\n" + "    {\n" + "      \"name\": \"cohortDestCosineV10\",\n"
        + "      \"type\": {\n" + "        \"type\": \"array\",\n" + "        \"items\": \"float\"\n" + "      },\n"
        + "      \"doc\": \"The dest member cohort embedding V10 for cosine similarity interaction.\",\n"
        + "      \"default\": []\n" + "    },\n" + "    {\n" + "      \"name\": \"cohortSrcCosineV11\",\n"
        + "      \"type\": {\n" + "        \"type\": \"array\",\n" + "        \"items\": \"float\"\n" + "      },\n"
        + "      \"doc\": \"The src member cohort embedding V11 for cosine similarity interaction.\",\n"
        + "      \"default\": []\n" + "    },\n" + "    {\n" + "      \"name\": \"cohortDestCosineV11\",\n"
        + "      \"type\": {\n" + "        \"type\": \"array\",\n" + "        \"items\": \"float\"\n" + "      },\n"
        + "      \"doc\": \"The dest member cohort embedding V11 for cosine similarity interaction.\",\n"
        + "      \"default\": []\n" + "    },\n" + "    {\n" + "      \"name\": \"cohortSrcCosineV12\",\n"
        + "      \"type\": {\n" + "        \"type\": \"array\",\n" + "        \"items\": \"float\"\n" + "      },\n"
        + "      \"doc\": \"The src member cohort embedding V12 for cosine similarity interaction.\",\n"
        + "      \"default\": []\n" + "    },\n" + "    {\n" + "      \"name\": \"cohortDestCosineV12\",\n"
        + "      \"type\": {\n" + "        \"type\": \"array\",\n" + "        \"items\": \"float\"\n" + "      },\n"
        + "      \"doc\": \"The dest member cohort embedding V12 for cosine similarity interaction.\",\n"
        + "      \"default\": []\n" + "    },\n" + "    {\n" + "      \"name\": \"personalizedMooCoeff\",\n"
        + "      \"type\": \"float\",\n"
        + "      \"doc\": \"Coefficients calculated from the personalized multi-objective optimization: more info at go/pMoo.\",\n"
        + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"personalizedMooLegacyCoeff\",\n"
        + "      \"type\": \"float\",\n"
        + "      \"doc\": \"Coefficients calculated from the personalized multi-objective optimization: more info at go/pMoo.\",\n"
        + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"personalizedMoopConnectCoeff\",\n"
        + "      \"type\": \"float\",\n"
        + "      \"doc\": \"Coefficients calculated from the personalized multi-objective optimization: more info at go/pMoo.\",\n"
        + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"gender\",\n" + "      \"type\": {\n"
        + "        \"type\": \"string\",\n" + "        \"avro.java.string\": \"String\"\n" + "      },\n"
        + "      \"doc\": \"Gender of member ['MALE','FEMALE', 'NON-BINARY','UNKNOWN'...]\",\n"
        + "      \"default\": \"\"\n" + "    },\n" + "    {\n"
        + "      \"name\": \"deepCCXFeedScoringSourceEmbeddingV2_2\",\n" + "      \"type\": {\n"
        + "        \"type\": \"array\",\n" + "        \"items\": \"float\"\n" + "      },\n"
        + "      \"doc\": \"souce side embedding from deep-CCX based on feed metapath features\",\n"
        + "      \"default\": []\n" + "    },\n" + "    {\n"
        + "      \"name\": \"deepCCXFeedScoringDestEmbeddingV2_2\",\n" + "      \"type\": {\n"
        + "        \"type\": \"array\",\n" + "        \"items\": \"float\"\n" + "      },\n"
        + "      \"doc\": \"dest side embedding from deep-CCX based on feed metapath features\",\n"
        + "      \"default\": []\n" + "    },\n" + "    {\n" + "      \"name\": \"srcMemberFilterReasons\",\n"
        + "      \"type\": {\n" + "        \"type\": \"array\",\n" + "        \"items\": \"int\"\n" + "      },\n"
        + "      \"doc\": \"Aggregated list of source member filter reason. Using int because Avro Enums are not evolvable. The original enum value is defined in pymk-member-filters MemberFilterReason.java. Example mapping includes but not limited to: 0 => BLACK_LIST, 1 => CELEBS, 2 => CLOSED\",\n"
        + "      \"default\": []\n" + "    },\n" + "    {\n" + "      \"name\": \"destMemberFilterReasons\",\n"
        + "      \"type\": {\n" + "        \"type\": \"array\",\n" + "        \"items\": \"int\"\n" + "      },\n"
        + "      \"doc\": \"Aggregated list of destination member filter reason. Using int because Avro Enums are not evolvable. The original enum value is defined in pymk-member-filters MemberFilterReason.java. Example mapping includes but not limited to: 0 => BLACK_LIST, 1 => CELEBS, 2 => CLOSED\",\n"
        + "      \"default\": []\n" + "    },\n" + "    {\n"
        + "      \"name\": \"deepCCXEVScoringSourceEmbeddingV3_0\",\n" + "      \"type\": {\n"
        + "        \"type\": \"array\",\n" + "        \"items\": \"float\"\n" + "      },\n"
        + "      \"doc\": \"source side embedding from deep-CCX based on EV metapath features\",\n"
        + "      \"default\": []\n" + "    },\n" + "    {\n"
        + "      \"name\": \"deepCCXEVScoringDestEmbeddingV3_0\",\n" + "      \"type\": {\n"
        + "        \"type\": \"array\",\n" + "        \"items\": \"float\"\n" + "      },\n"
        + "      \"doc\": \"dest side embedding from deep-CCX based on EV metapath features\",\n"
        + "      \"default\": []\n" + "    },\n" + "    {\n" + "      \"name\": \"pMooVersions\",\n"
        + "      \"type\": {\n" + "        \"type\": \"array\",\n" + "        \"items\": {\n"
        + "          \"type\": \"string\",\n" + "          \"avro.java.string\": \"String\"\n" + "        }\n"
        + "      },\n" + "      \"doc\": \"pMoo version IDs\",\n" + "      \"default\": []\n" + "    },\n" + "    {\n"
        + "      \"name\": \"pMooCoefficientIds\",\n" + "      \"type\": {\n" + "        \"type\": \"array\",\n"
        + "        \"items\": {\n" + "          \"type\": \"string\",\n"
        + "          \"avro.java.string\": \"String\"\n" + "        }\n" + "      },\n"
        + "      \"doc\": \"terms for different FPR combinations in pMoo\",\n" + "      \"default\": []\n" + "    },\n"
        + "    {\n" + "      \"name\": \"pMooCoefficientValues\",\n" + "      \"type\": {\n"
        + "        \"type\": \"array\",\n" + "        \"items\": \"float\"\n" + "      },\n"
        + "      \"doc\": \"pMoo coefficient values\",\n" + "      \"default\": []\n" + "    },\n" + "    {\n"
        + "      \"name\": \"memberCareerTransitionEmbedding\",\n" + "      \"type\": {\n"
        + "        \"type\": \"array\",\n" + "        \"items\": \"float\"\n" + "      },\n"
        + "      \"doc\": \"Member career transition embedding\",\n" + "      \"default\": []\n" + "    },\n"
        + "    {\n" + "      \"name\": \"latitude\",\n" + "      \"type\": \"float\",\n"
        + "      \"doc\": \"The latitude fetched by the first geo entity\",\n" + "      \"default\": -1\n" + "    },\n"
        + "    {\n" + "      \"name\": \"longitude\",\n" + "      \"type\": \"float\",\n"
        + "      \"doc\": \"The longitude fetched by the first geo entity\",\n" + "      \"default\": -1\n" + "    },\n"
        + "    {\n" + "      \"name\": \"sourceImpressionCount\",\n" + "      \"type\": \"int\",\n"
        + "      \"doc\": \"Unique impression count as a viewer in 56 days happened 60 days ago\",\n"
        + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"sourceInvitationCount\",\n"
        + "      \"type\": \"int\",\n"
        + "      \"doc\": \"The number of member connection invitations sent by the source member in 56 days happened 60 days ago\",\n"
        + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"sourceInvitationAcceptCount\",\n"
        + "      \"type\": \"int\",\n"
        + "      \"doc\": \"The number of accepted member connection invitations sent by the source member since 56 days ahead of 60 days ago\",\n"
        + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"destImpressionCount\",\n"
        + "      \"type\": \"int\",\n"
        + "      \"doc\": \"Unique impression count as a viewee in 56 days happened 60 days ago\",\n"
        + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"destInvitationCount\",\n"
        + "      \"type\": \"int\",\n"
        + "      \"doc\": \"The number of member connection invitations received by the dest member in 56 days happened 60 days ago\",\n"
        + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"destInvitationAcceptCount\",\n"
        + "      \"type\": \"int\",\n"
        + "      \"doc\": \"The number of accepted member connection invitations received by the dest member since 56 days ahead of 60 days ago\",\n"
        + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"pymkSourceImpressionCount\",\n"
        + "      \"type\": \"int\",\n"
        + "      \"doc\": \"The number of pymk impressions viewed by a viewer in 56 days happened 60 days ago.\",\n"
        + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"pymkSourceInvitationCount\",\n"
        + "      \"type\": \"int\",\n"
        + "      \"doc\": \"The number of pymk invitations sent by a source member in 56 days happened 60 days ago.\",\n"
        + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"pymkSourceInvitationAcceptCount\",\n"
        + "      \"type\": \"int\",\n"
        + "      \"doc\": \"The number of accepted pymk invitations sent by a source member since 56 days ahead of 60 days ago.\",\n"
        + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"pymkDestImpressionCount\",\n"
        + "      \"type\": \"int\",\n"
        + "      \"doc\": \"The number of pymk impressions being viewed by a viewee in 56 days happened 60 days ago.\",\n"
        + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"pymkDestInvitationCount\",\n"
        + "      \"type\": \"int\",\n"
        + "      \"doc\": \"The number of pymk invitations received by a dest member in 56 days happened 60 days ago.\",\n"
        + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"pymkDestInvitationAcceptCount\",\n"
        + "      \"type\": \"int\",\n"
        + "      \"doc\": \"The number of accepted pymk invitations received by a dest member since 56 days ahead of 60 days ago.\",\n"
        + "      \"default\": 0\n" + "    },\n" + "    {\n" + "      \"name\": \"memberSpecialties\",\n"
        + "      \"type\": {\n" + "        \"type\": \"array\",\n" + "        \"items\": \"float\"\n" + "      },\n"
        + "      \"doc\": \"Member specialty embedding. The top member specialties are stored, with the specialtyID extracted. Each member has fewer than 5 specialties. More details can be found in go/specialty\",\n"
        + "      \"default\": []\n" + "    }\n" + "  ]\n" + "}";

   Schema newValueSchema = AvroSchemaParseUtils.parseSchemaFromJSONStrictValidation(valueSchemaStr1);
   Schema existingValueSchema = AvroSchemaParseUtils.parseSchemaFromJSONStrictValidation(valueSchemaStr2);
   Schema newSuperSetSchema = AvroSchemaUtils.generateSuperSetSchema(existingValueSchema, newValueSchema);
   Assert.assertTrue(new SchemaEntry(1, valueSchemaStr2).isNewSchemaCompatible(new SchemaEntry(2, newSuperSetSchema), DirectionalSchemaCompatibilityType.FULL));
  }

  @Test
  public void  testAddValueSchema() {
    String valueSchemaStr1 = "\"long\"";
    String valueSchemaStr2 = "\"string\"";

    SchemaData schemaData = new SchemaData("test_store");
    schemaData.addValueSchema(new SchemaEntry(1, valueSchemaStr1));
    schemaData.addValueSchema(new SchemaEntry(2, valueSchemaStr2));

    Assert.assertEquals(schemaData.getSchemaID(new SchemaEntry(10, valueSchemaStr1)), 1);
    Assert.assertEquals(schemaData.getSchemaID(new SchemaEntry(10, valueSchemaStr2)), 2);
    Assert.assertEquals(schemaData.getMaxValueSchemaId(), 2);
    Assert.assertEquals(new SchemaEntry(10, valueSchemaStr1), schemaData.getValueSchema(1));
  }
}
