package com.linkedin.venice.schema;

import com.linkedin.venice.schema.avro.DirectionalSchemaCompatibilityType;
import org.testng.Assert;
import org.testng.annotations.Test;

public class TestSchemaData {
  @Test
  public void testAddKeySchema() {
    String keySchemaStr = "\"string\"";
    int id = 1;
    SchemaEntry entry = new SchemaEntry(id, keySchemaStr);
    SchemaData schemaData = new SchemaData("test_store");
    schemaData.setKeySchema(entry);

    SchemaEntry keySchema = schemaData.getKeySchema();
    Assert.assertEquals(keySchema.getId(), 1);
    Assert.assertEquals(keySchemaStr, keySchema.getSchema().toString());
  }

  @Test
  public void  testAddValueSchema() {
    String valueSchemaStr1 = "{\n" + "   \"type\":\"record\",\n" + "   \"name\":\"memberFeaturesObject\",\n"
        + "   \"namespace\":\"com.linkedin.pymk.schema\",\n" + "   \"fields\":[\n" + "      {\n"
        + "         \"name\":\"activityLevel\",\n" + "         \"type\":\"int\",\n"
        + "         \"doc\":\"Member activity level, from 0-4. 0-4 means: 0(Onboarding), 1(Dormant), 2(OneByOne), 3(OneByThree), 4(FourbyFour)\",\n"
        + "         \"default\":-1\n" + "      },\n" + "      {\n" + "         \"name\":\"connectionCount\",\n"
        + "         \"type\":\"int\",\n" + "         \"doc\":\"The total connection count of a member.\",\n"
        + "         \"default\":0\n" + "      },\n" + "      {\n" + "         \"name\":\"lastConnectionAcceptedAt\",\n"
        + "         \"type\":\"int\",\n"
        + "         \"doc\":\"The Unix timestamp (seconds) of the most recently accepted connection.\",\n"
        + "         \"default\":0\n" + "      },\n" + "      {\n" + "         \"name\":\"invReceivedCount\",\n"
        + "         \"type\":\"int\",\n"
        + "         \"doc\":\"The number of member connection invitations received by the member in the past 28 days.\",\n"
        + "         \"default\":0\n" + "      },\n" + "      {\n" + "         \"name\":\"pymkSourceImpressionCount\",\n"
        + "         \"type\":\"int\",\n"
        + "         \"doc\":\"The number of pymk impressions viewed by a viewer in 56 days happened 60 days ago.\",\n"
        + "         \"default\":0\n" + "      },\n" + "      {\n" + "         \"name\":\"pymkDestImpressionCount\",\n"
        + "         \"type\":\"int\",\n"
        + "         \"doc\":\"The number of pymk impressions being viewed by a viewee in 56 days happened 60 days ago.\",\n"
        + "         \"default\":0\n" + "      },\n" + "      {\n" + "         \"name\":\"sourceInvitationCount\",\n"
        + "         \"type\":\"int\",\n"
        + "         \"doc\":\"The number of generic invitations sent by a source member in 56 days happened 60 days ago.\",\n"
        + "         \"default\":0\n" + "      },\n" + "      {\n" + "         \"name\":\"destInvitationCount\",\n"
        + "         \"type\":\"int\",\n"
        + "         \"doc\":\"The number of generic invitations received by a dest member in 56 days happened 60 days ago.\",\n"
        + "         \"default\":0\n" + "      },\n" + "      {\n" + "         \"name\":\"pymkSourceInvitationCount\",\n"
        + "         \"type\":\"int\",\n"
        + "         \"doc\":\"The number of pymk invitations sent by a source member in 56 days happened 60 days ago.\",\n"
        + "         \"default\":0\n" + "      },\n" + "      {\n" + "         \"name\":\"pymkDestInvitationCount\",\n"
        + "         \"type\":\"int\",\n"
        + "         \"doc\":\"The number of pymk invitations received by a dest member in 56 days happened 60 days ago.\",\n"
        + "         \"default\":0\n" + "      },\n" + "      {\n"
        + "         \"name\":\"sourceInvitationAcceptCount\",\n" + "         \"type\":\"int\",\n"
        + "         \"doc\":\"The number of accepted generic invitations sent by a source member since 56 days ahead of 60 days ago.\",\n"
        + "         \"default\":0\n" + "      },\n" + "      {\n" + "         \"name\":\"destInvitationAcceptCount\",\n"
        + "         \"type\":\"int\",\n"
        + "         \"doc\":\"The number of accepted generic invitations received by a dest member since 56 days ahead of 60 days ago.\",\n"
        + "         \"default\":0\n" + "      },\n" + "      {\n"
        + "         \"name\":\"pymkSourceInvitationAcceptCount\",\n" + "         \"type\":\"int\",\n"
        + "         \"doc\":\"The number of accepted pymk invitations sent by a source member since 56 days ahead of 60 days ago.\",\n"
        + "         \"default\":0\n" + "      },\n" + "      {\n"
        + "         \"name\":\"pymkDestInvitationAcceptCount\",\n" + "         \"type\":\"int\",\n"
        + "         \"doc\":\"The number of accepted pymk invitations received by a dest member since 56 days ahead of 60 days ago.\",\n"
        + "         \"default\":0\n" + "      },\n" + "      {\n" + "         \"name\":\"publicContributor\",\n"
        + "         \"type\":\"int\",\n"
        + "         \"doc\":\"The member has like/commented/shared or created content that has viral action\",\n"
        + "         \"default\":0\n" + "      },\n" + "      {\n" + "         \"name\":\"privateContributor\",\n"
        + "         \"type\":\"int\",\n"
        + "         \"doc\":\"The member has contributed through private messaging or inMail\",\n"
        + "         \"default\":0\n" + "      },\n" + "      {\n" + "         \"name\":\"totalActiveConnections\",\n"
        + "         \"type\":\"int\",\n"
        + "         \"doc\":\"The number of connections of a member who have made at least 1 contribution (like/comment/share/message) in the past 28 days\",\n"
        + "         \"default\":0\n" + "      },\n" + "      {\n" + "         \"name\":\"privateActiveConnections\",\n"
        + "         \"type\":\"int\",\n"
        + "         \"doc\":\"The number of connections of a member who have made at least 1 private contribution (message/inMail) in the past 28 days\",\n"
        + "         \"default\":0\n" + "      },\n" + "      {\n" + "         \"name\":\"publicActiveConnections\",\n"
        + "         \"type\":\"int\",\n"
        + "         \"doc\":\"The number of connections of a member who have made at least 1 public contribution (like/comment/share/publish) in the past 28 days\",\n"
        + "         \"default\":0\n" + "      },\n" + "      {\n" + "         \"name\":\"allContributionCount\",\n"
        + "         \"type\":\"int\",\n"
        + "         \"doc\":\"The total number of contributions (likes, comments, shares, private messages/inmails) that the member contributed in the past 28 days\",\n"
        + "         \"default\":0\n" + "      },\n" + "      {\n" + "         \"name\":\"likeCount\",\n"
        + "         \"type\":\"int\",\n"
        + "         \"doc\":\"The number of likes that the member contributed in the past 28 days\",\n"
        + "         \"default\":0\n" + "      },\n" + "      {\n" + "         \"name\":\"commentCount\",\n"
        + "         \"type\":\"int\",\n"
        + "         \"doc\":\"The number of comments that the member contributed in the past 28 days\",\n"
        + "         \"default\":0\n" + "      },\n" + "      {\n" + "         \"name\":\"shareCount\",\n"
        + "         \"type\":\"int\",\n"
        + "         \"doc\":\"The number of shares that the member contributed in the past 28 days\",\n"
        + "         \"default\":0\n" + "      },\n" + "      {\n" + "         \"name\":\"articleContribCount\",\n"
        + "         \"type\":\"int\",\n"
        + "         \"doc\":\"The total number of articles that a member has contributed\",\n"
        + "         \"default\":0\n" + "      },\n" + "      {\n" + "         \"name\":\"privateContribCount\",\n"
        + "         \"type\":\"int\",\n"
        + "         \"doc\":\"The number of private messages or inMails that the member has sent in the past 28 days\",\n"
        + "         \"default\":0\n" + "      },\n" + "      {\n" + "         \"name\":\"allFeedContribCount\",\n"
        + "         \"type\":\"int\",\n"
        + "         \"doc\":\"The total number of contributions(likes, comments, shares) in Feed that the member contributed in the past 28 days\",\n"
        + "         \"default\":0\n" + "      },\n" + "      {\n" + "         \"name\":\"feedLikeCount\",\n"
        + "         \"type\":\"int\",\n"
        + "         \"doc\":\"The total number of likes that the member contributed in Feed in the past 28 days\",\n"
        + "         \"default\":0\n" + "      },\n" + "      {\n" + "         \"name\":\"feedCommentCount\",\n"
        + "         \"type\":\"int\",\n"
        + "         \"doc\":\"The total number of comments that the member contributed in Feed in the past 28 days\",\n"
        + "         \"default\":0\n" + "      },\n" + "      {\n" + "         \"name\":\"feedShareCount\",\n"
        + "         \"type\":\"int\",\n"
        + "         \"doc\":\"The total number of shares that the member contributed in Feed in the past 28 days\",\n"
        + "         \"default\":0\n" + "      },\n" + "      {\n"
        + "         \"name\":\"boostFactorConsumerOptimus\",\n" + "         \"type\":\"float\",\n"
        + "         \"doc\":\"Boost factor to be applied to all destinations -- optimus consumer-side experiment\",\n"
        + "         \"default\":0\n" + "      },\n" + "      {\n" + "         \"name\":\"utilityConsumerOptimus\",\n"
        + "         \"type\":\"float\",\n"
        + "         \"doc\":\"Utility score for being destination -- optimus consumer-side experiment\",\n"
        + "         \"default\":0\n" + "      },\n" + "      {\n" + "         \"name\":\"skillsEmbedding\",\n"
        + "         \"type\":{\n" + "            \"type\":\"array\",\n" + "            \"items\":\"float\"\n"
        + "         },\n" + "         \"doc\":\"The member skills embedding\",\n" + "         \"default\":[\n"
        + "            \n" + "         ]\n" + "      },\n" + "      {\n" + "         \"name\":\"titlesEmbedding\",\n"
        + "         \"type\":{\n" + "            \"type\":\"array\",\n" + "            \"items\":\"float\"\n"
        + "         },\n" + "         \"doc\":\"The member titles embedding\",\n" + "         \"default\":[\n"
        + "            \n" + "         ]\n" + "      },\n" + "      {\n" + "         \"name\":\"companiesEmbedding\",\n"
        + "         \"type\":{\n" + "            \"type\":\"array\",\n" + "            \"items\":\"float\"\n"
        + "         },\n" + "         \"doc\":\"The member companies embedding\",\n" + "         \"default\":[\n"
        + "            \n" + "         ]\n" + "      },\n" + "      {\n" + "         \"name\":\"schoolsEmbedding\",\n"
        + "         \"type\":{\n" + "            \"type\":\"array\",\n" + "            \"items\":\"float\"\n"
        + "         },\n" + "         \"doc\":\"The member schools embedding\",\n" + "         \"default\":[\n"
        + "            \n" + "         ]\n" + "      },\n" + "      {\n" + "         \"name\":\"needleEmbedding\",\n"
        + "         \"type\":{\n" + "            \"type\":\"array\",\n" + "            \"items\":\"float\"\n"
        + "         },\n" + "         \"doc\":\"The member needle embedding\",\n" + "         \"default\":[\n"
        + "            \n" + "         ]\n" + "      },\n" + "      {\n" + "         \"name\":\"needleEmbeddingA\",\n"
        + "         \"type\":{\n" + "            \"type\":\"array\",\n" + "            \"items\":\"float\"\n"
        + "         },\n"
        + "         \"doc\":\"The experimental needle embedding A,  which is reserved for fast model iteration\",\n"
        + "         \"default\":[\n" + "            \n" + "         ]\n" + "      },\n" + "      {\n"
        + "         \"name\":\"needleEmbeddingB\",\n" + "         \"type\":{\n" + "            \"type\":\"array\",\n"
        + "            \"items\":\"float\"\n" + "         },\n"
        + "         \"doc\":\"The experimental needle embedding B,  which is reserved for fast model iteration\",\n"
        + "         \"default\":[\n" + "            \n" + "         ]\n" + "      },\n" + "      {\n"
        + "         \"name\":\"deepCCXFeedScoringSourceEmbeddingV2_2\",\n" + "         \"type\":{\n"
        + "            \"type\":\"array\",\n" + "            \"items\":\"float\"\n" + "         },\n"
        + "         \"doc\":\"souce side embedding from deep-CCX based on feed metapath features\",\n"
        + "         \"default\":[\n" + "            \n" + "         ]\n" + "      },\n" + "      {\n"
        + "         \"name\":\"deepCCXFeedScoringDestEmbeddingV2_2\",\n" + "         \"type\":{\n"
        + "            \"type\":\"array\",\n" + "            \"items\":\"float\"\n" + "         },\n"
        + "         \"doc\":\"dest side embedding from deep-CCX based on feed metapath features\",\n"
        + "         \"default\":[\n" + "            \n" + "         ]\n" + "      },\n" + "      {\n"
        + "         \"name\":\"deepCCXEVScoringSourceEmbeddingV3_0\",\n" + "         \"type\":{\n"
        + "            \"type\":\"array\",\n" + "            \"items\":\"float\"\n" + "         },\n"
        + "         \"doc\":\"source side embedding from deep-CCX based on EV metapath features\",\n"
        + "         \"default\":[\n" + "            \n" + "         ]\n" + "      },\n" + "      {\n"
        + "         \"name\":\"deepCCXEVScoringDestEmbeddingV3_0\",\n" + "         \"type\":{\n"
        + "            \"type\":\"array\",\n" + "            \"items\":\"float\"\n" + "         },\n"
        + "         \"doc\":\"dest side embedding from deep-CCX based on EV metapath features\",\n"
        + "         \"default\":[\n" + "            \n" + "         ]\n" + "      },\n" + "      {\n"
        + "         \"name\":\"rlActionV0\",\n" + "         \"type\":{\n" + "            \"type\":\"array\",\n"
        + "            \"items\":\"float\"\n" + "         },\n"
        + "         \"doc\":\"The viewer action vector based on reinforcement learning (v0)\",\n"
        + "         \"default\":[\n" + "            \n" + "         ]\n" + "      },\n" + "      {\n"
        + "         \"name\":\"rlActionV1\",\n" + "         \"type\":{\n" + "            \"type\":\"array\",\n"
        + "            \"items\":\"float\"\n" + "         },\n"
        + "         \"doc\":\"The viewer action vector based on reinforcement learning (v1)\",\n"
        + "         \"default\":[\n" + "            \n" + "         ]\n" + "      },\n" + "      {\n"
        + "         \"name\":\"profileCompanies\",\n" + "         \"type\":{\n" + "            \"type\":\"array\",\n"
        + "            \"items\":{\n" + "               \"type\":\"record\",\n"
        + "               \"name\":\"profileCompanies\",\n" + "               \"fields\":[\n" + "                  {\n"
        + "                     \"name\":\"companyId\",\n" + "                     \"type\":\"int\",\n"
        + "                     \"doc\":\"\",\n" + "                     \"default\":0\n" + "                  },\n"
        + "                  {\n" + "                     \"name\":\"industryId\",\n"
        + "                     \"type\":\"int\",\n" + "                     \"doc\":\"\",\n"
        + "                     \"default\":0\n" + "                  },\n" + "                  {\n"
        + "                     \"name\":\"isCurrent\",\n" + "                     \"type\":\"boolean\",\n"
        + "                     \"doc\":\"\",\n" + "                     \"default\":false\n" + "                  },\n"
        + "                  {\n" + "                     \"name\":\"position\",\n"
        + "                     \"type\":{\n" + "                        \"type\":\"string\",\n"
        + "                        \"avro.java.string\":\"String\"\n" + "                     },\n"
        + "                     \"doc\":\"\",\n" + "                     \"default\":\"\"\n" + "                  }\n"
        + "               ]\n" + "            }\n" + "         },\n" + "         \"doc\":\"Profile company info\",\n"
        + "         \"default\":[\n" + "            \n" + "         ]\n" + "      },\n" + "      {\n"
        + "         \"name\":\"profileSchools\",\n" + "         \"type\":{\n" + "            \"type\":\"array\",\n"
        + "            \"items\":{\n" + "               \"type\":\"record\",\n"
        + "               \"name\":\"profileSchools\",\n" + "               \"fields\":[\n" + "                  {\n"
        + "                     \"name\":\"schoolId\",\n" + "                     \"type\":\"int\",\n"
        + "                     \"doc\":\"deprecated\",\n" + "                     \"default\":0\n"
        + "                  },\n" + "                  {\n" + "                     \"name\":\"organizationId\",\n"
        + "                     \"type\":\"long\",\n" + "                     \"doc\":\"\",\n"
        + "                     \"default\":0\n" + "                  },\n" + "                  {\n"
        + "                     \"name\":\"cipCodeId\",\n" + "                     \"type\":{\n"
        + "                        \"type\":\"string\",\n" + "                        \"avro.java.string\":\"String\"\n"
        + "                     },\n" + "                     \"doc\":\"\",\n"
        + "                     \"default\":\"\"\n" + "                  },\n" + "                  {\n"
        + "                     \"name\":\"degreeId\",\n" + "                     \"type\":\"int\",\n"
        + "                     \"doc\":\"\",\n" + "                     \"default\":0\n" + "                  },\n"
        + "                  {\n" + "                     \"name\":\"startTime\",\n"
        + "                     \"type\":\"long\",\n" + "                     \"doc\":\"\",\n"
        + "                     \"default\":-1\n" + "                  }\n" + "               ]\n" + "            }\n"
        + "         },\n" + "         \"doc\":\"Profile school info\",\n" + "         \"default\":[\n"
        + "            \n" + "         ]\n" + "      },\n" + "      {\n" + "         \"name\":\"profileGeo\",\n"
        + "         \"type\":{\n" + "            \"type\":\"string\",\n"
        + "            \"avro.java.string\":\"String\"\n" + "         },\n" + "         \"doc\":\"Profile geo\",\n"
        + "         \"default\":\"\"\n" + "      },\n" + "      {\n" + "         \"name\":\"memberLanguages\",\n"
        + "         \"type\":{\n" + "            \"type\":\"array\",\n" + "            \"items\":{\n"
        + "               \"type\":\"string\",\n" + "               \"avro.java.string\":\"String\"\n"
        + "            }\n" + "         },\n"
        + "         \"doc\":\"Inferred languages over a threshold for a member.\",\n" + "         \"default\":[\n"
        + "            \n" + "         ]\n" + "      },\n" + "      {\n" + "         \"name\":\"profileRegion\",\n"
        + "         \"type\":\"long\",\n"
        + "         \"doc\":\"Profile region, using the MARKET_AREA of bing geo, corresponding to the former region code.\",\n"
        + "         \"default\":-1\n" + "      },\n" + "      {\n" + "         \"name\":\"profileOccupationId\",\n"
        + "         \"type\":\"int\",\n"
        + "         \"doc\":\"The standardized supertitle id with the highest confidence score from the most recent position of the user. The name occupation id is aligned with that in om_segment.\",\n"
        + "         \"default\":-1\n" + "      },\n" + "      {\n" + "         \"name\":\"latitude\",\n"
        + "         \"type\":\"float\",\n" + "         \"doc\":\"The latitude fetched by the first geo entity\",\n"
        + "         \"default\":200\n" + "      },\n" + "      {\n" + "         \"name\":\"longitude\",\n"
        + "         \"type\":\"float\",\n" + "         \"doc\":\"The longitude fetched by the first geo entity\",\n"
        + "         \"default\":200\n" + "      },\n" + "      {\n" + "         \"name\":\"deltaPcreate\",\n"
        + "         \"type\":\"float\",\n"
        + "         \"doc\":\"Member feedback sensitivity (for creation) -- value is between 0 and 1.\",\n"
        + "         \"default\":0\n" + "      },\n" + "      {\n" + "         \"name\":\"followsAsCTA\",\n"
        + "         \"type\":\"boolean\",\n" + "         \"doc\":\"Member who sets follows as CTA\",\n"
        + "         \"default\":false\n" + "      },\n" + "      {\n"
        + "         \"name\":\"blockUnwantedInvitesOrReconnectInvites\",\n" + "         \"type\":\"boolean\",\n"
        + "         \"doc\":\"This setting is true for a Member who allows connection request from people who know the members email or appear in the members imported contact list.\",\n"
        + "         \"default\":false\n" + "      },\n" + "      {\n"
        + "         \"name\":\"isInternationallyOriented\",\n" + "         \"type\":\"boolean\",\n"
        + "         \"doc\":\"If a member is internationally oriented, as defined in go/intloriented\",\n"
        + "         \"default\":false\n" + "      },\n" + "      {\n" + "         \"name\":\"memberGroups\",\n"
        + "         \"type\":{\n" + "            \"type\":\"array\",\n" + "            \"items\":\"long\"\n"
        + "         },\n"
        + "         \"doc\":\"A list of healthy groups ids (go/healthyGroups) which the member is part of.\",\n"
        + "         \"default\":[\n" + "            \n" + "         ]\n" + "      },\n" + "      {\n"
        + "         \"name\":\"organizationsFollowed\",\n" + "         \"type\":{\n"
        + "            \"type\":\"array\",\n" + "            \"items\":\"long\"\n" + "         },\n"
        + "         \"doc\":\"Organizations followed by the member, such as schools and companies.\",\n"
        + "         \"default\":[\n" + "            \n" + "         ]\n" + "      },\n" + "      {\n"
        + "         \"name\":\"srcMemberFilters\",\n" + "         \"type\":\"long\",\n"
        + "         \"doc\":\"If a member is in the pymk offline source member filters, it will be 1, otherwise it will be 0\",\n"
        + "         \"default\":0\n" + "      },\n" + "      {\n" + "         \"name\":\"destMemberFilters\",\n"
        + "         \"type\":\"long\",\n"
        + "         \"doc\":\"If a member is in the pymk offline dest member filters, it will be 1, otherwise it will be 0\",\n"
        + "         \"default\":0\n" + "      },\n" + "      {\n" + "         \"name\":\"mlc\",\n"
        + "         \"type\":{\n" + "            \"type\":\"string\",\n"
        + "            \"avro.java.string\":\"String\"\n" + "         },\n"
        + "         \"doc\":\"Member Life Cycle V3 assignment for this member\",\n" + "         \"default\":\"\"\n"
        + "      },\n" + "      {\n" + "         \"name\":\"lastActiveTime\",\n" + "         \"type\":\"long\",\n"
        + "         \"doc\":\"Epoch time in milliseconds of the last time the member was active on LinkedIn\",\n"
        + "         \"default\":0\n" + "      },\n" + "      {\n"
        + "         \"name\":\"careerInterestSurveyResponseActive\",\n" + "         \"type\":\"float\",\n"
        + "         \"doc\":\"Whether activity-inferred career interest survey response is active. More info: https://iwww.corp.linkedin.com/wiki/cf/display/ENGS/Member+Intent\",\n"
        + "         \"default\":0\n" + "      },\n" + "      {\n" + "         \"name\":\"hiringManagerIntent\",\n"
        + "         \"type\":\"float\",\n"
        + "         \"doc\":\"Whether member has intent to hire. Talent professionals excluded. More info: https://iwww.corp.linkedin.com/wiki/cf/display/ENGS/Member+Intent\",\n"
        + "         \"default\":0\n" + "      },\n" + "      {\n" + "         \"name\":\"contentContributionIntent\",\n"
        + "         \"type\":\"float\",\n"
        + "         \"doc\":\"Intent to feed content post and share. More info: https://iwww.corp.linkedin.com/wiki/cf/display/ENGS/Member+Intent\",\n"
        + "         \"default\":0\n" + "      },\n" + "      {\n" + "         \"name\":\"contentConsumerIntent\",\n"
        + "         \"type\":\"float\",\n"
        + "         \"doc\":\"Intent to article read and video play(non-auto), More info: https://iwww.corp.linkedin.com/wiki/cf/display/ENGS/Member+Intent\",\n"
        + "         \"default\":0\n" + "      },\n" + "      {\n"
        + "         \"name\":\"personalizedMoopConnectCoeff\",\n" + "         \"type\":\"float\",\n"
        + "         \"doc\":\"Coefficients calculated from the personalized multi-objective optimization: more info at go/pMoo.\",\n"
        + "         \"default\":0\n" + "      },\n" + "      {\n" + "         \"name\":\"pMooVersions\",\n"
        + "         \"type\":{\n" + "            \"type\":\"array\",\n" + "            \"items\":{\n"
        + "               \"type\":\"string\",\n" + "               \"avro.java.string\":\"String\"\n"
        + "            }\n" + "         },\n" + "         \"doc\":\"pMoo version IDs\",\n" + "         \"default\":[\n"
        + "            \n" + "         ]\n" + "      },\n" + "      {\n" + "         \"name\":\"pMooCoefficientIds\",\n"
        + "         \"type\":{\n" + "            \"type\":\"array\",\n" + "            \"items\":{\n"
        + "               \"type\":\"string\",\n" + "               \"avro.java.string\":\"String\"\n"
        + "            }\n" + "         },\n" + "         \"doc\":\"terms for different FPR combinations in pMoo\",\n"
        + "         \"default\":[\n" + "            \n" + "         ]\n" + "      },\n" + "      {\n"
        + "         \"name\":\"pMooCoefficientValues\",\n" + "         \"type\":{\n"
        + "            \"type\":\"array\",\n" + "            \"items\":\"float\"\n" + "         },\n"
        + "         \"doc\":\"pMoo coefficient values\",\n" + "         \"default\":[\n" + "            \n"
        + "         ]\n" + "      },\n" + "      {\n" + "         \"name\":\"gender\",\n" + "         \"type\":{\n"
        + "            \"type\":\"string\",\n" + "            \"avro.java.string\":\"String\"\n" + "         },\n"
        + "         \"doc\":\"Gender of member ['MALE','FEMALE', 'NON-BINARY','UNKNOWN'...]\",\n"
        + "         \"default\":\"\"\n" + "      },\n" + "      {\n" + "         \"name\":\"careerStartYears\",\n"
        + "         \"type\":\"int\",\n"
        + "         \"doc\":\"Number of years from the member's earliest education end time to today\",\n"
        + "         \"default\":-21\n" + "      },\n" + "      {\n" + "         \"name\":\"srcMemberFilterReasons\",\n"
        + "         \"type\":{\n" + "            \"type\":\"array\",\n" + "            \"items\":\"int\"\n"
        + "         },\n"
        + "         \"doc\":\"Aggregated list of source member filter reason. Using int because Avro Enums are not evolvable. The original enum value is defined in pymk-member-filters MemberFilterReason.java. Example mapping includes but not limited to: 0 => BLACK_LIST, 1 => CELEBS, 2 => CLOSED\",\n"
        + "         \"default\":[\n" + "            \n" + "         ]\n" + "      },\n" + "      {\n"
        + "         \"name\":\"destMemberFilterReasons\",\n" + "         \"type\":{\n"
        + "            \"type\":\"array\",\n" + "            \"items\":\"int\"\n" + "         },\n"
        + "         \"doc\":\"Aggregated list of destination member filter reason. Using int because Avro Enums are not evolvable. The original enum value is defined in pymk-member-filters MemberFilterReason.java. Example mapping includes but not limited to: 0 => BLACK_LIST, 1 => CELEBS, 2 => CLOSED\",\n"
        + "         \"default\":[\n" + "            \n" + "         ]\n" + "      },\n" + "      {\n"
        + "         \"name\":\"memberCareerTransitionEmbedding\",\n" + "         \"type\":{\n"
        + "            \"type\":\"array\",\n" + "            \"items\":\"float\"\n" + "         },\n"
        + "         \"doc\":\"Member career transition embedding\",\n" + "         \"default\":[\n" + "            \n"
        + "         ]\n" + "      },\n" + "      {\n" + "         \"name\":\"memberSpecialties\",\n"
        + "         \"type\":{\n" + "            \"type\":\"array\",\n" + "            \"items\":\"float\"\n"
        + "         },\n"
        + "         \"doc\":\"Member specialty embedding. The top member specialties are stored, with the specialtyID extracted. Each member has fewer than 5 specialties. More details can be found in go/specialty\",\n"
        + "         \"default\":[\n" + "            \n" + "         ]\n" + "      }\n" + "   ]\n" + "}";
    String valueSchemaStr2 = "{\"type\":\"record\",\"name\":\"memberFeaturesObject\",\"namespace\":\"com.linkedin.pymk.schema\",\"fields\":[{\"name\":\"visitProbabilityForInvite\",\"type\":\"float\",\"doc\":\"The probability of a member visiting the site after sending this member an invitation. The range of this value will between 0 to 1. The higher the value, the more likely that member will visit the site. \"},{\"name\":\"activityLevel\",\"type\":\"int\",\"doc\":\"Member activity level, from 0-4. 0-4 means: 0(Onboarding), 1(Dormant), 2(OneByOne), 3(OneByThree), 4(FourbyFour)\",\"default\":-1},{\"name\":\"connectionCount\",\"type\":\"int\",\"doc\":\"The total connection count of a member.\",\"default\":0},{\"name\":\"lastConnectionAcceptedAt\",\"type\":\"int\",\"doc\":\"The Unix timestamp (seconds) of the most recently accepted connection.\",\"default\":0},{\"name\":\"pVisitModel\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Different lix treatment(pvisit models) for computing pvisit score.\",\"default\":\"\"},{\"name\":\"pVisitBasicModelScore\",\"type\":\"float\",\"doc\":\"The score is computed based on the pVisit basic model which is simply member visit probability.\"},{\"name\":\"pVisitEqmGainModelScore\",\"type\":\"float\",\"doc\":\"The pvisit score is computed based on a model that uses potential eQM gain as weight during model training. eQM_gain model slightly prefer member visit from who has more eQM gain.\"},{\"name\":\"invReceivedCount\",\"type\":\"int\",\"doc\":\"The number of member connection invitations received by the member in the past 7 days.\",\"default\":0},{\"name\":\"publicContributor\",\"type\":\"int\",\"doc\":\"The member has like/commented/shared or created content that has viral action\",\"default\":0},{\"name\":\"privateContributor\",\"type\":\"int\",\"doc\":\"The member has contributed through private messaging or inMail\",\"default\":0},{\"name\":\"totalActiveConnections\",\"type\":\"int\",\"doc\":\"The number of connections of a member who have made at least 1 contribution (like/comment/share/message) in the past 7 days\",\"default\":0},{\"name\":\"privateActiveConnections\",\"type\":\"int\",\"doc\":\"The number of connections of a member who have made at least 1 private contribution (message/inMail) in the past 7 days\",\"default\":0},{\"name\":\"publicActiveConnections\",\"type\":\"int\",\"doc\":\"The number of connections of a member who have made at least 1 public contribution (like/comment/share/publish) in the past 7 days\",\"default\":0},{\"name\":\"allContributionCount\",\"type\":\"int\",\"doc\":\"The total number of contributions (likes, comments, shares, private messages/inmails) that the member contributed in the past 7 days\",\"default\":0},{\"name\":\"likeCount\",\"type\":\"int\",\"doc\":\"The number of likes that the member contributed in the past 7 days\",\"default\":0},{\"name\":\"commentCount\",\"type\":\"int\",\"doc\":\"The number of comments that the member contributed in the past 7 days\",\"default\":0},{\"name\":\"shareCount\",\"type\":\"int\",\"doc\":\"The number of shares that the member contributed in the past 7 days\",\"default\":0},{\"name\":\"articleContribCount\",\"type\":\"int\",\"doc\":\"The total number of articles that a member has contributed\",\"default\":0},{\"name\":\"privateContribCount\",\"type\":\"int\",\"doc\":\"The number of private messages or inMails that the member has sent in the past 7 days\",\"default\":0},{\"name\":\"allFeedContribCount\",\"type\":\"int\",\"doc\":\"The total number of contributions(likes, comments, shares) in Feed that the member contributed in the past 7 days\",\"default\":0},{\"name\":\"feedLikeCount\",\"type\":\"int\",\"doc\":\"The total number of likes that the member contributed in Feed in the past 7 days\",\"default\":0},{\"name\":\"feedCommentCount\",\"type\":\"int\",\"doc\":\"The total number of comments that the member contributed in Feed in the past 7 days\",\"default\":0},{\"name\":\"feedShareCount\",\"type\":\"int\",\"doc\":\"The total number of shares that the member contributed in Feed in the past 7 days\",\"default\":0},{\"name\":\"boostFactorConsumerOptimus\",\"type\":\"float\",\"doc\":\"Boost factor to be applied to all destinations -- optimus consumer-side experiment\"},{\"name\":\"utilityConsumerOptimus\",\"type\":\"float\",\"doc\":\"Utility score for being destination -- optimus consumer-side experiment\"},{\"name\":\"skillsEmbedding\",\"type\":{\"type\":\"array\",\"items\":\"float\"},\"doc\":\"The member skills embedding\",\"default\":[]},{\"name\":\"titlesEmbedding\",\"type\":{\"type\":\"array\",\"items\":\"float\"},\"doc\":\"The member titles embedding\",\"default\":[]},{\"name\":\"companiesEmbedding\",\"type\":{\"type\":\"array\",\"items\":\"float\"},\"doc\":\"The member companies embedding\",\"default\":[]},{\"name\":\"schoolsEmbedding\",\"type\":{\"type\":\"array\",\"items\":\"float\"},\"doc\":\"The member schools embedding\",\"default\":[]},{\"name\":\"needleEmbedding\",\"type\":{\"type\":\"array\",\"items\":\"float\"},\"doc\":\"The member needle embedding\",\"default\":[]},{\"name\":\"needleEmbeddingA\",\"type\":{\"type\":\"array\",\"items\":\"float\"},\"doc\":\"The experimental needle embedding A,  which is reserved for fast model iteration\",\"default\":[]},{\"name\":\"needleEmbeddingB\",\"type\":{\"type\":\"array\",\"items\":\"float\"},\"doc\":\"The experimental needle embedding B,  which is reserved for fast model iteration\",\"default\":[]},{\"name\":\"pymkSrcCosineV0\",\"type\":{\"type\":\"array\",\"items\":\"float\"},\"doc\":\"The src member pymk embedding for cosine similarity interaction\",\"default\":[]},{\"name\":\"pymkDestCosineV0\",\"type\":{\"type\":\"array\",\"items\":\"float\"},\"doc\":\"The dest member pymk embedding for cosine similarity interaction\",\"default\":[]},{\"name\":\"cohortSrcCosineV0\",\"type\":{\"type\":\"array\",\"items\":\"float\"},\"doc\":\"The dest member cohort embedding V0 for cosine similarity interaction. V0 uses only cohort mvp features.\",\"default\":[]},{\"name\":\"cohortDestCosineV0\",\"type\":{\"type\":\"array\",\"items\":\"float\"},\"doc\":\"The dest member cohort embedding V0 for cosine similarity interaction. V0 uses only cohort mvp features.\",\"default\":[]},{\"name\":\"cohortSrcCosineV1\",\"type\":{\"type\":\"array\",\"items\":\"float\"},\"doc\":\"The src member cohort embedding V1 for cosine similarity interaction. V1 uses cohort mvp+transformed features\",\"default\":[]},{\"name\":\"cohortDestCosineV1\",\"type\":{\"type\":\"array\",\"items\":\"float\"},\"doc\":\"The src member cohort embedding V1 for cosine similarity interaction. V1 uses cohort mvp+transformed features\",\"default\":[]},{\"name\":\"cohortSrcCosineV2\",\"type\":{\"type\":\"array\",\"items\":\"float\"},\"doc\":\"The src member cohort embedding V2 for cosine similarity interaction.\",\"default\":[]},{\"name\":\"cohortDestCosineV2\",\"type\":{\"type\":\"array\",\"items\":\"float\"},\"doc\":\"The dest member cohort embedding V2 for cosine similarity interaction.\",\"default\":[]},{\"name\":\"cohortSrcCosineV3\",\"type\":{\"type\":\"array\",\"items\":\"float\"},\"doc\":\"The src member cohort embedding V3 for cosine similarity interaction.\",\"default\":[]},{\"name\":\"cohortDestCosineV3\",\"type\":{\"type\":\"array\",\"items\":\"float\"},\"doc\":\"The dest member cohort embedding V3 for cosine similarity interaction.\",\"default\":[]},{\"name\":\"cohortSrcHadamardV4\",\"type\":{\"type\":\"array\",\"items\":\"float\"},\"doc\":\"The src member cohort embedding embedding V4 for hadamard interaction.\",\"default\":[]},{\"name\":\"cohortDestHadamardV4\",\"type\":{\"type\":\"array\",\"items\":\"float\"},\"doc\":\"The dest member cohort embedding embedding V4 for hadamard interaction.\",\"default\":[]},{\"name\":\"cohortSrcHadamardV5\",\"type\":{\"type\":\"array\",\"items\":\"float\"},\"doc\":\"The src member cohort embedding embedding V5 for hadamard interaction.\",\"default\":[]},{\"name\":\"cohortDestHadamardV5\",\"type\":{\"type\":\"array\",\"items\":\"float\"},\"doc\":\"The dest member cohort embedding embedding V5 for hadamard interaction.\",\"default\":[]},{\"name\":\"rlActionV0\",\"type\":{\"type\":\"array\",\"items\":\"float\"},\"doc\":\"The viewer action vector based on reinforcement learning (v0)\",\"default\":[]},{\"name\":\"rlActionV1\",\"type\":{\"type\":\"array\",\"items\":\"float\"},\"doc\":\"The viewer action vector based on reinforcement learning (v1)\",\"default\":[]},{\"name\":\"cohortSrcHadamardV6\",\"type\":{\"type\":\"array\",\"items\":\"float\"},\"doc\":\"The src member cohort embedding embedding V6 for hadamard product interaction.\",\"default\":[]},{\"name\":\"cohortDestHadamardV6\",\"type\":{\"type\":\"array\",\"items\":\"float\"},\"doc\":\"The dest member cohort embedding embedding V6 for hadamard product interaction.\",\"default\":[]},{\"name\":\"cohortSrcCosineV7\",\"type\":{\"type\":\"array\",\"items\":\"float\"},\"doc\":\"The src member cohort embedding embedding V7 for cosine similarity interaction.\",\"default\":[]},{\"name\":\"cohortDestCosineV7\",\"type\":{\"type\":\"array\",\"items\":\"float\"},\"doc\":\"The dest member cohort embedding embedding V7 for cosine similarity interaction.\",\"default\":[]},{\"name\":\"cohortSrcCosineV8\",\"type\":{\"type\":\"array\",\"items\":\"float\"},\"doc\":\"The src member cohort embedding embedding V8 for cosine similarity interaction.\",\"default\":[]},{\"name\":\"cohortDestCosineV8\",\"type\":{\"type\":\"array\",\"items\":\"float\"},\"doc\":\"The dest member cohort embedding embedding V8 for cosine similarity interaction.\",\"default\":[]},{\"name\":\"profileCompanies\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"profileCompanies\",\"fields\":[{\"name\":\"companyId\",\"type\":\"int\",\"doc\":\"\",\"default\":0},{\"name\":\"industryId\",\"type\":\"int\",\"doc\":\"\",\"default\":0},{\"name\":\"isCurrent\",\"type\":\"boolean\",\"doc\":\"\",\"default\":false},{\"name\":\"position\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"\",\"default\":\"\"}]}},\"doc\":\"Profile company info\",\"default\":[]},{\"name\":\"profileSchools\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"profileSchools\",\"fields\":[{\"name\":\"schoolId\",\"type\":\"int\",\"doc\":\"\",\"default\":0},{\"name\":\"cipCodeId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"\",\"default\":\"\"},{\"name\":\"degreeId\",\"type\":\"int\",\"doc\":\"\",\"default\":0},{\"name\":\"startTime\",\"type\":\"long\",\"doc\":\"\",\"default\":-1},{\"name\":\"organizationId\",\"type\":\"long\",\"doc\":\"\",\"default\":0}]}},\"doc\":\"Profile school info\",\"default\":[]},{\"name\":\"profileGeo\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Profile geo\",\"default\":\"\"},{\"name\":\"memberLanguages\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},\"doc\":\"Inferred languages over a threshold for a member.\",\"default\":[]},{\"name\":\"profileRegion\",\"type\":\"long\",\"doc\":\"Profile region, using the MARKET_AREA of bing geo, corresponding to the former region code.\",\"default\":-1},{\"name\":\"profileOccupationId\",\"type\":\"int\",\"doc\":\"The standardized supertitle id with the highest confidence score from the most recent position of the user. The name occupation id is aligned with that in om_segment.\",\"default\":-1},{\"name\":\"deltaPcreate\",\"type\":\"float\",\"doc\":\"Member feedback sensitivity (for creation) -- value is between 0 and 1.\"},{\"name\":\"followsAsCTA\",\"type\":\"boolean\",\"doc\":\"Member who sets follows as CTA\",\"default\":false},{\"name\":\"blockUnwantedInvitesOrReconnectInvites\",\"type\":\"boolean\",\"doc\":\"This setting is true for a Member who allows connection request from people who know the members email or appear in the members imported contact list.\",\"default\":false},{\"name\":\"isInternationallyOriented\",\"type\":\"boolean\",\"doc\":\"If a member is internationally oriented, as defined in go/intloriented\",\"default\":false},{\"name\":\"memberGroups\",\"type\":{\"type\":\"array\",\"items\":\"long\"},\"doc\":\"A list of healthy groups ids (go/healthyGroups) which the member is part of.\",\"default\":[]},{\"name\":\"organizationsFollowed\",\"type\":{\"type\":\"array\",\"items\":\"long\"},\"doc\":\"Organizations followed by the member, such as schools and companies.\",\"default\":[]},{\"name\":\"srcMemberFilters\",\"type\":\"long\",\"doc\":\"If a member is in the pymk offline source member filters, it will be 1, otherwise it will be 0\",\"default\":0},{\"name\":\"destMemberFilters\",\"type\":\"long\",\"doc\":\"If a member is in the pymk offline dest member filters, it will be 1, otherwise it will be 0\",\"default\":0},{\"name\":\"mlcV3\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Member Life Cycle V3 assignment for this member\",\"default\":\"\"},{\"name\":\"lastActiveTime\",\"type\":\"long\",\"doc\":\"Epoch time in milliseconds of the last time the member was active on LinkedIn\",\"default\":0},{\"name\":\"mlc\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Member Life Cycle V3 assignment for this member\",\"default\":\"\"},{\"name\":\"cohortSrcCosineV9\",\"type\":{\"type\":\"array\",\"items\":\"float\"},\"doc\":\"The src member cohort embedding V9 for cosine similarity interaction.\",\"default\":[]},{\"name\":\"cohortDestCosineV9\",\"type\":{\"type\":\"array\",\"items\":\"float\"},\"doc\":\"The dest member cohort embedding V9 for cosine similarity interaction.\",\"default\":[]},{\"name\":\"careerInterestSurveyResponseActive\",\"type\":\"float\",\"doc\":\"Whether activity-inferred career interest survey response is active. More info: https://iwww.corp.linkedin.com/wiki/cf/display/ENGS/Member+Intent\"},{\"name\":\"hiringManagerIntent\",\"type\":\"float\",\"doc\":\"Whether member has intent to hire. Talent professionals excluded. More info: https://iwww.corp.linkedin.com/wiki/cf/display/ENGS/Member+Intent\"},{\"name\":\"contentContributionIntent\",\"type\":\"float\",\"doc\":\"Intent to feed content post and share. More info: https://iwww.corp.linkedin.com/wiki/cf/display/ENGS/Member+Intent\"},{\"name\":\"contentConsumerIntent\",\"type\":\"float\",\"doc\":\"Intent to article read and video play(non-auto), More info: https://iwww.corp.linkedin.com/wiki/cf/display/ENGS/Member+Intent\"},{\"name\":\"cohortSrcCosineV10\",\"type\":{\"type\":\"array\",\"items\":\"float\"},\"doc\":\"The src member cohort embedding V10 for cosine similarity interaction.\",\"default\":[]},{\"name\":\"cohortDestCosineV10\",\"type\":{\"type\":\"array\",\"items\":\"float\"},\"doc\":\"The dest member cohort embedding V10 for cosine similarity interaction.\",\"default\":[]},{\"name\":\"cohortSrcCosineV11\",\"type\":{\"type\":\"array\",\"items\":\"float\"},\"doc\":\"The src member cohort embedding V11 for cosine similarity interaction.\",\"default\":[]},{\"name\":\"cohortDestCosineV11\",\"type\":{\"type\":\"array\",\"items\":\"float\"},\"doc\":\"The dest member cohort embedding V11 for cosine similarity interaction.\",\"default\":[]},{\"name\":\"cohortSrcCosineV12\",\"type\":{\"type\":\"array\",\"items\":\"float\"},\"doc\":\"The src member cohort embedding V12 for cosine similarity interaction.\",\"default\":[]},{\"name\":\"cohortDestCosineV12\",\"type\":{\"type\":\"array\",\"items\":\"float\"},\"doc\":\"The dest member cohort embedding V12 for cosine similarity interaction.\",\"default\":[]},{\"name\":\"personalizedMooCoeff\",\"type\":\"float\",\"doc\":\"Coefficients calculated from the personalized multi-objective optimization: more info at go/pMoo.\"},{\"name\":\"personalizedMooLegacyCoeff\",\"type\":\"float\",\"doc\":\"Coefficients calculated from the personalized multi-objective optimization: more info at go/pMoo.\"},{\"name\":\"personalizedMoopConnectCoeff\",\"type\":\"float\",\"doc\":\"Coefficients calculated from the personalized multi-objective optimization: more info at go/pMoo.\"},{\"name\":\"gender\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Gender of member ['MALE','FEMALE', 'NON-BINARY','UNKNOWN'...]\",\"default\":\"\"},{\"name\":\"deepCCXFeedScoringSourceEmbeddingV2_2\",\"type\":{\"type\":\"array\",\"items\":\"float\"},\"doc\":\"souce side embedding from deep-CCX based on feed metapath features\",\"default\":[]},{\"name\":\"deepCCXFeedScoringDestEmbeddingV2_2\",\"type\":{\"type\":\"array\",\"items\":\"float\"},\"doc\":\"dest side embedding from deep-CCX based on feed metapath features\",\"default\":[]},{\"name\":\"srcMemberFilterReasons\",\"type\":{\"type\":\"array\",\"items\":\"int\"},\"doc\":\"Aggregated list of source member filter reason. Using int because Avro Enums are not evolvable. The original enum value is defined in pymk-member-filters MemberFilterReason.java. Example mapping includes but not limited to: 0 => BLACK_LIST, 1 => CELEBS, 2 => CLOSED\",\"default\":[]},{\"name\":\"destMemberFilterReasons\",\"type\":{\"type\":\"array\",\"items\":\"int\"},\"doc\":\"Aggregated list of destination member filter reason. Using int because Avro Enums are not evolvable. The original enum value is defined in pymk-member-filters MemberFilterReason.java. Example mapping includes but not limited to: 0 => BLACK_LIST, 1 => CELEBS, 2 => CLOSED\",\"default\":[]},{\"name\":\"deepCCXEVScoringSourceEmbeddingV3_0\",\"type\":{\"type\":\"array\",\"items\":\"float\"},\"doc\":\"source side embedding from deep-CCX based on EV metapath features\",\"default\":[]},{\"name\":\"deepCCXEVScoringDestEmbeddingV3_0\",\"type\":{\"type\":\"array\",\"items\":\"float\"},\"doc\":\"dest side embedding from deep-CCX based on EV metapath features\",\"default\":[]},{\"name\":\"pMooVersions\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},\"doc\":\"pMoo version IDs\",\"default\":[]},{\"name\":\"pMooCoefficientIds\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},\"doc\":\"terms for different FPR combinations in pMoo\",\"default\":[]},{\"name\":\"pMooCoefficientValues\",\"type\":{\"type\":\"array\",\"items\":\"float\"},\"doc\":\"pMoo coefficient values\",\"default\":[]},{\"name\":\"memberCareerTransitionEmbedding\",\"type\":{\"type\":\"array\",\"items\":\"float\"},\"doc\":\"Member career transition embedding\",\"default\":[]},{\"name\":\"latitude\",\"type\":\"float\",\"doc\":\"The latitude fetched by the first geo entity\"},{\"name\":\"longitude\",\"type\":\"float\",\"doc\":\"The longitude fetched by the first geo entity\"},{\"name\":\"sourceImpressionCount\",\"type\":\"int\",\"doc\":\"Unique impression count as a viewer in 56 days happened 60 days ago\",\"default\":0},{\"name\":\"sourceInvitationCount\",\"type\":\"int\",\"doc\":\"The number of member connection invitations sent by the source member in 56 days happened 60 days ago\",\"default\":0},{\"name\":\"sourceInvitationAcceptCount\",\"type\":\"int\",\"doc\":\"The number of accepted member connection invitations sent by the source member since 56 days ahead of 60 days ago\",\"default\":0},{\"name\":\"destImpressionCount\",\"type\":\"int\",\"doc\":\"Unique impression count as a viewee in 56 days happened 60 days ago\",\"default\":0},{\"name\":\"destInvitationCount\",\"type\":\"int\",\"doc\":\"The number of member connection invitations received by the dest member in 56 days happened 60 days ago\",\"default\":0},{\"name\":\"destInvitationAcceptCount\",\"type\":\"int\",\"doc\":\"The number of accepted member connection invitations received by the dest member since 56 days ahead of 60 days ago\",\"default\":0},{\"name\":\"pymkSourceImpressionCount\",\"type\":\"int\",\"doc\":\"The number of pymk impressions viewed by a viewer in 56 days happened 60 days ago.\",\"default\":0},{\"name\":\"pymkSourceInvitationCount\",\"type\":\"int\",\"doc\":\"The number of pymk invitations sent by a source member in 56 days happened 60 days ago.\",\"default\":0},{\"name\":\"pymkSourceInvitationAcceptCount\",\"type\":\"int\",\"doc\":\"The number of accepted pymk invitations sent by a source member since 56 days ahead of 60 days ago.\",\"default\":0},{\"name\":\"pymkDestImpressionCount\",\"type\":\"int\",\"doc\":\"The number of pymk impressions being viewed by a viewee in 56 days happened 60 days ago.\",\"default\":0},{\"name\":\"pymkDestInvitationCount\",\"type\":\"int\",\"doc\":\"The number of pymk invitations received by a dest member in 56 days happened 60 days ago.\",\"default\":0},{\"name\":\"pymkDestInvitationAcceptCount\",\"type\":\"int\",\"doc\":\"The number of accepted pymk invitations received by a dest member since 56 days ahead of 60 days ago.\",\"default\":0},{\"name\":\"memberSpecialties\",\"type\":{\"type\":\"array\",\"items\":\"float\"},\"doc\":\"Member specialty embedding. The top member specialties are stored, with the specialtyID extracted. Each member has fewer than 5 specialties. More details can be found in go/specialty\",\"default\":[]},{\"name\":\"careerStartYears\",\"type\":\"int\",\"doc\":\"Number of years from the member's earliest education end time to today\",\"default\":-21}]} ";

    Assert.assertTrue(new SchemaEntry(1, valueSchemaStr1).isNewSchemaCompatible(new SchemaEntry(2, valueSchemaStr2), DirectionalSchemaCompatibilityType.FULL));

  }
}
