/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_linkedin_venice_cuda_GPUDaVinciRecordTransformer */

#ifndef _Included_com_linkedin_venice_cuda_GPUDaVinciRecordTransformer
#define _Included_com_linkedin_venice_cuda_GPUDaVinciRecordTransformer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_linkedin_venice_cuda_GPUDaVinciRecordTransformer
 * Method:    nativeInitializeGPU
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_linkedin_venice_cuda_GPUDaVinciRecordTransformer_nativeInitializeGPU
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_linkedin_venice_cuda_GPUDaVinciRecordTransformer
 * Method:    nativeShutdownGPU
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_linkedin_venice_cuda_GPUDaVinciRecordTransformer_nativeShutdownGPU
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_linkedin_venice_cuda_GPUDaVinciRecordTransformer
 * Method:    nativeCreateHashMap
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_linkedin_venice_cuda_GPUDaVinciRecordTransformer_nativeCreateHashMap
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_linkedin_venice_cuda_GPUDaVinciRecordTransformer
 * Method:    nativeDestroyHashMap
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_linkedin_venice_cuda_GPUDaVinciRecordTransformer_nativeDestroyHashMap
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_linkedin_venice_cuda_GPUDaVinciRecordTransformer
 * Method:    nativePut
 * Signature: (J[B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_linkedin_venice_cuda_GPUDaVinciRecordTransformer_nativePut
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray);

/*
 * Class:     com_linkedin_venice_cuda_GPUDaVinciRecordTransformer
 * Method:    nativeGet
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_linkedin_venice_cuda_GPUDaVinciRecordTransformer_nativeGet
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_linkedin_venice_cuda_GPUDaVinciRecordTransformer
 * Method:    nativeRemove
 * Signature: (J[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_linkedin_venice_cuda_GPUDaVinciRecordTransformer_nativeRemove
  (JNIEnv *, jobject, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
