cluster.name=venice-cluster0
listener.port=7777
listener.ssl.port=7778
system.schema.cluster.name=venice-cluster0
zookeeper.address=zookeeper.dc-1.venicedb.io:2181
sslToStorageNodes=false
kafka.zk.address=zookeeper.dc-1.venicedb.io:2181
cluster.to.d2=venice-cluster0:venice-discovery
kafka.bootstrap.servers=kafka.dc-1.venicedb.io:9092
router.storage.node.client.type=APACHE_HTTP_ASYNC_CLIENT
