/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.linkedin.venice.compute.protocol.request;

@SuppressWarnings("all")
public class CosineSimilarity extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"CosineSimilarity\",\"namespace\":\"com.linkedin.venice.compute.protocol.request\",\"fields\":[{\"name\":\"field\",\"type\":\"string\",\"doc\":\"The field in the original value record, which will used to execute cosine-similarity calculation\"},{\"name\":\"cosSimilarityParam\",\"type\":{\"type\":\"array\",\"items\":\"float\"},\"doc\":\"The passed feature vector, which will be used to execute cosine-similarity calculation against the field in the original value record\"},{\"name\":\"resultFieldName\",\"type\":\"string\",\"doc\":\"The field name used to store the calculated result\"}]}");
  /** The field in the original value record, which will used to execute cosine-similarity calculation */
  public java.lang.CharSequence field;
  /** The passed feature vector, which will be used to execute cosine-similarity calculation against the field in the original value record */
  public java.util.List<java.lang.Float> cosSimilarityParam;
  /** The field name used to store the calculated result */
  public java.lang.CharSequence resultFieldName;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return field;
    case 1: return cosSimilarityParam;
    case 2: return resultFieldName;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: field = (java.lang.CharSequence)value$; break;
    case 1: cosSimilarityParam = (java.util.List<java.lang.Float>)value$; break;
    case 2: resultFieldName = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}
