package com.linkedin.venice.controller;

import java.util.Map;


/**
 * Accessor user to get/update the last execution id and the generated id from a storage.
 */
public interface ExecutionIdAccessor {
  /**
   * Get the id for the last succeed operation in the given cluster.
   */
  Long getLastSucceededExecutionId(String clusterName);

  /**
   * Update the id of the last succeed operation in the given cluster.
   */
  void updateLastSucceededExecutionId(String clusterName, Long lastSucceedExecutionId);

  /**
   * Get the execution id map that contains the last succeeded operation in the given cluster for each store.
   */
  Map<String, Long> getLastSucceededExecutionIdMap(String clusterName);

  /**
   * Update the execution id map that contains the last succeeded operation in the given cluster for each store.
   */
  void updateLastSucceededExecutionIdMap(String clusterName, String storeName, Long lastSucceededExecutionId);

  /**
   * Get the last id which is generated by execution tracker in the give cluster.
   */
  Long getLastGeneratedExecutionId(String clusterName);

  /**
   * Update the last id which is generated by execution tracker in the given cluster.
   */
  void updateLastGeneratedExecutionId(String clusterName, Long lastGeneratedExecutionId);

  /**
   * Read the current value from ZK and try to increment the value by 1 and write it back to ZK.
   * @return  updated execution id.
   */
  Long incrementAndGetExecutionId(String clusterName);
}
