/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.linkedin.venice.participant.protocol;

@SuppressWarnings("all")
public class ParticipantMessageValue extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"ParticipantMessageValue\",\"namespace\":\"com.linkedin.venice.participant.protocol\",\"fields\":[{\"name\":\"messageType\",\"type\":\"int\",\"doc\":\"0 => KillPushJob\"},{\"name\":\"messageUnion\",\"type\":[{\"type\":\"record\",\"name\":\"KillPushJob\",\"fields\":[{\"name\":\"timestamp\",\"type\":\"long\",\"default\":-1}]}],\"doc\":\"This contains the main body of the message\"}]}");
  /** 0 => KillPushJob */
  public int messageType;
  /** This contains the main body of the message */
  public java.lang.Object messageUnion;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return messageType;
    case 1: return messageUnion;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: messageType = (java.lang.Integer)value$; break;
    case 1: messageUnion = (java.lang.Object)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}
