package com.linkedin.davinci.store.rocksdb;

import com.linkedin.davinci.config.VeniceServerConfig;
import com.linkedin.davinci.config.VeniceStoreVersionConfig;
import com.linkedin.davinci.store.AbstractStorageEngineTest;
import com.linkedin.davinci.store.StorageEngine;
import com.linkedin.venice.meta.PersistenceType;
import com.linkedin.venice.meta.Version;
import com.linkedin.venice.utils.Utils;
import com.linkedin.venice.utils.VeniceProperties;
import java.io.File;
import java.util.Set;
import org.testng.Assert;
import org.testng.annotations.Test;


public class RocksDBStorageEngineFactoryTest {
  @Test
  public void testRocksDBCreation() {
    VeniceProperties veniceServerProperties = AbstractStorageEngineTest.getServerProperties(PersistenceType.ROCKS_DB);
    VeniceServerConfig serverConfig = new VeniceServerConfig(veniceServerProperties);

    RocksDBStorageEngineFactory factory = new RocksDBStorageEngineFactory(serverConfig);

    final String testStore = Version.composeKafkaTopic(Utils.getUniqueString("test_store"), 1);
    VeniceStoreVersionConfig testStoreConfig =
        new VeniceStoreVersionConfig(testStore, veniceServerProperties, PersistenceType.ROCKS_DB);
    StorageEngine storeEngine = factory.getStorageEngine(testStoreConfig);
    Assert.assertTrue(
        storeEngine instanceof RocksDBStorageEngine,
        "Database generated by" + " 'RocksDBStorageEngineFactory' must be 'RocksDBStorageEngine' instance");
  }

  @Test
  public void testGetPersistedStoreNames() {
    // Create two databases
    VeniceProperties veniceServerProperties = AbstractStorageEngineTest.getServerProperties(PersistenceType.ROCKS_DB);
    VeniceServerConfig serverConfig = new VeniceServerConfig(veniceServerProperties);

    RocksDBStorageEngineFactory factory = new RocksDBStorageEngineFactory(serverConfig);

    final String testStore1 = Version.composeKafkaTopic(Utils.getUniqueString("test_store"), 1);
    VeniceStoreVersionConfig testStoreConfig1 =
        new VeniceStoreVersionConfig(testStore1, veniceServerProperties, PersistenceType.ROCKS_DB);
    factory.getStorageEngine(testStoreConfig1);
    final String testStore2 = Version.composeKafkaTopic(Utils.getUniqueString("test_store"), 1);
    VeniceStoreVersionConfig testStoreConfig2 =
        new VeniceStoreVersionConfig(testStore2, veniceServerProperties, PersistenceType.ROCKS_DB);
    factory.getStorageEngine(testStoreConfig2);
    factory.close();
    // Retrieve all the persisted stores from disk
    Set<String> storeNameSet = factory.getPersistedStoreNames();
    Assert.assertEquals(storeNameSet.size(), 2);
    Assert.assertTrue(storeNameSet.contains(testStore1));
    Assert.assertTrue(storeNameSet.contains(testStore2));
  }

  @Test
  public void testRemoveStorageEngine() {
    // Create one databases
    VeniceProperties veniceServerProperties = AbstractStorageEngineTest.getServerProperties(PersistenceType.ROCKS_DB);
    VeniceServerConfig serverConfig = new VeniceServerConfig(veniceServerProperties);

    RocksDBStorageEngineFactory factory = new RocksDBStorageEngineFactory(serverConfig);

    final String testStore = Version.composeKafkaTopic(Utils.getUniqueString("test_store"), 1);
    VeniceStoreVersionConfig testStoreConfig =
        new VeniceStoreVersionConfig(testStore, veniceServerProperties, PersistenceType.ROCKS_DB);
    StorageEngine storageEngine = factory.getStorageEngine(testStoreConfig);
    // drop the database
    factory.removeStorageEngine(storageEngine);
    factory.close();
    // Retrieve all the persisted stores from disk
    Set<String> storeNameSet = factory.getPersistedStoreNames();
    Assert.assertEquals(storeNameSet.size(), 0);
  }

  @Test
  public void testRemoveStorageEnginePartition() {
    // Create one databases
    VeniceProperties veniceServerProperties = AbstractStorageEngineTest.getServerProperties(PersistenceType.ROCKS_DB);
    VeniceServerConfig serverConfig = new VeniceServerConfig(veniceServerProperties);

    RocksDBStorageEngineFactory factory = new RocksDBStorageEngineFactory(serverConfig);

    final String testStore = Version.composeKafkaTopic(Utils.getUniqueString("test_store"), 1);
    VeniceStoreVersionConfig testStoreConfig =
        new VeniceStoreVersionConfig(testStore, veniceServerProperties, PersistenceType.ROCKS_DB);
    StorageEngine storageEngine = factory.getStorageEngine(testStoreConfig);
    File file = new File(factory.getRocksDBPath(testStore, 1));
    file.mkdirs();
    Assert.assertTrue(file.exists());
    // drop the database
    factory.removeStorageEngine(storageEngine);
    factory.removeStorageEnginePartition(testStore, 1);
    factory.close();
    Assert.assertFalse(file.exists());
  }

  @Test
  public void testAddNewPartitionAfterRemoving() {
    VeniceProperties veniceServerProperties = AbstractStorageEngineTest.getServerProperties(PersistenceType.ROCKS_DB);
    VeniceServerConfig serverConfig = new VeniceServerConfig(veniceServerProperties);
    RocksDBStorageEngineFactory factory = new RocksDBStorageEngineFactory(serverConfig);

    final String testStore = Version.composeKafkaTopic(Utils.getUniqueString("test_store_"), 1);
    VeniceStoreVersionConfig testStoreConfig =
        new VeniceStoreVersionConfig(testStore, veniceServerProperties, PersistenceType.ROCKS_DB);
    StorageEngine storeEngine = factory.getStorageEngine(testStoreConfig);
    storeEngine.addStoragePartitionIfAbsent(1);
    storeEngine.dropPartition(1);
    factory.removeStorageEngine(storeEngine);
    // This could happen when re-balance happens or the pre-created partitions get moved/removed.
    storeEngine = factory.getStorageEngine(testStoreConfig);
    storeEngine.addStoragePartitionIfAbsent(1);

    factory.removeStorageEngine(storeEngine);
  }
}
