/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.linkedin.venice.status.protocol;

@SuppressWarnings("all")
/** Key part of the heartbeat sent by a push job. Each key represents a session of heartbeats from one push job instance */
public class BatchJobHeartbeatKey extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"BatchJobHeartbeatKey\",\"namespace\":\"com.linkedin.venice.status.protocol\",\"fields\":[{\"name\":\"storeName\",\"type\":\"string\",\"doc\":\"Name of the store which the running push job instance is pushing data to\"},{\"name\":\"storeVersion\",\"type\":\"int\",\"doc\":\"Version of the store which the running push job instance is pushing data to\"}]}");
  /** Name of the store which the running push job instance is pushing data to */
  public java.lang.CharSequence storeName;
  /** Version of the store which the running push job instance is pushing data to */
  public int storeVersion;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return storeName;
    case 1: return storeVersion;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: storeName = (java.lang.CharSequence)value$; break;
    case 1: storeVersion = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}
