/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.linkedin.venice.admin.protocol.response;

@SuppressWarnings("all")
public class ServerConfigSnapshot extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"ServerConfigSnapshot\",\"namespace\":\"com.linkedin.venice.admin.protocol.response\",\"fields\":[{\"name\":\"configMap\",\"type\":{\"type\":\"map\",\"values\":\"string\"},\"doc\":\"A map that contains all the configs in runtime\",\"default\":{}}]}");
  /** A map that contains all the configs in runtime */
  public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> configMap;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return configMap;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: configMap = (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}
