package com.linkedin.davinci.store;

public enum StoragePartitionAdjustmentTrigger {
  BEGIN_BLOB_TRANSFER, END_BLOB_TRANSFER, CHECK_DATABASE_INTEGRITY, BEGIN_BATCH_PUSH, END_BATCH_PUSH, PREPARE_FOR_READ,
  PROMOTE_TO_LEADER, DEMOTE_TO_FOLLOWER, REOPEN_WITH_DEFAULTS
}
