package com.linkedin.venice.controllerapi;

import com.linkedin.venice.stats.dimensions.VeniceDimensionTestFixture;
import com.linkedin.venice.stats.dimensions.VeniceMetricsDimensions;
import com.linkedin.venice.utils.CollectionUtils;
import java.util.Map;
import org.testng.annotations.Test;


public class ControllerRouteDimensionTest {
  @Test
  public void testDimensionInterface() {
    Map<ControllerRoute, String> expectedValues = CollectionUtils.<ControllerRoute, String>mapBuilder()
        .put(ControllerRoute.UNKNOWN_ROUTE, "unknown_route")
        .put(ControllerRoute.REQUEST_TOPIC, "request_topic")
        .put(ControllerRoute.EMPTY_PUSH, "empty_push")
        .put(ControllerRoute.END_OF_PUSH, "end_of_push")
        .put(ControllerRoute.STORE, "store")
        .put(ControllerRoute.NEW_STORE, "new_store")
        .put(ControllerRoute.CHECK_RESOURCE_CLEANUP_FOR_STORE_CREATION, "check_resource_cleanup_for_store_creation")
        .put(ControllerRoute.STORE_MIGRATION_ALLOWED, "store_migration_allowed")
        .put(ControllerRoute.MIGRATE_STORE, "migrate_store")
        .put(ControllerRoute.AUTO_MIGRATE_STORE, "auto_migrate_store")
        .put(ControllerRoute.COMPLETE_MIGRATION, "complete_migration")
        .put(ControllerRoute.ABORT_MIGRATION, "abort_migration")
        .put(ControllerRoute.DELETE_STORE, "delete_store")
        .put(ControllerRoute.UPDATE_STORE, "update_store")
        .put(ControllerRoute.SET_VERSION, "set_version")
        .put(ControllerRoute.ROLLBACK_TO_BACKUP_VERSION, "rollback_to_backup_version")
        .put(ControllerRoute.AGGREGATED_HEALTH_STATUS, "aggregated_health_status")
        .put(ControllerRoute.ROLL_FORWARD_TO_FUTURE_VERSION, "roll_forward_to_future_version")
        .put(ControllerRoute.ENABLE_STORE, "enable_store")
        .put(ControllerRoute.DELETE_ALL_VERSIONS, "delete_all_versions")
        .put(ControllerRoute.DELETE_OLD_VERSION, "delete_old_version")
        .put(ControllerRoute.UPDATE_CLUSTER_CONFIG, "update_cluster_config")
        .put(ControllerRoute.UPDATE_DARK_CLUSTER_CONFIG, "update_dark_cluster_config")
        .put(ControllerRoute.JOB, "job")
        .put(ControllerRoute.KILL_OFFLINE_PUSH_JOB, "kill_offline_push_job")
        .put(ControllerRoute.LIST_STORES, "list_stores")
        .put(ControllerRoute.CLEAN_EXECUTION_IDS, "clean_execution_ids")
        .put(ControllerRoute.LIST_CHILD_CLUSTERS, "list_child_clusters")
        .put(ControllerRoute.LIST_NODES, "list_nodes")
        .put(ControllerRoute.CLUSTER_HEALTH_STORES, "cluster_health_stores")
        .put(ControllerRoute.ClUSTER_HEALTH_INSTANCES, "cluster_health_instances")
        .put(ControllerRoute.LIST_REPLICAS, "list_replicas")
        .put(ControllerRoute.NODE_REPLICAS, "node_replicas")
        .put(ControllerRoute.NODE_REMOVABLE, "node_removable")
        .put(ControllerRoute.NODE_REPLICAS_READINESS, "node_replicas_readiness")
        .put(ControllerRoute.ALLOW_LIST_ADD_NODE, "allow_list_add_node")
        .put(ControllerRoute.ALLOW_LIST_REMOVE_NODE, "allow_list_remove_node")
        .put(ControllerRoute.REMOVE_NODE, "remove_node")
        .put(ControllerRoute.SKIP_ADMIN_MESSAGE, "skip_admin_message")
        .put(ControllerRoute.GET_KEY_SCHEMA, "get_key_schema")
        .put(ControllerRoute.ADD_VALUE_SCHEMA, "add_value_schema")
        .put(ControllerRoute.ADD_DERIVED_SCHEMA, "add_derived_schema")
        .put(ControllerRoute.SET_OWNER, "set_owner")
        .put(ControllerRoute.SET_PARTITION_COUNT, "set_partition_count")
        .put(ControllerRoute.GET_ALL_VALUE_SCHEMA, "get_all_value_schema")
        .put(ControllerRoute.GET_ALL_VALUE_AND_DERIVED_SCHEMA, "get_all_value_and_derived_schema")
        .put(ControllerRoute.GET_VALUE_SCHEMA, "get_value_schema")
        .put(ControllerRoute.GET_VALUE_SCHEMA_ID, "get_value_schema_id")
        .put(ControllerRoute.GET_VALUE_OR_DERIVED_SCHEMA_ID, "get_value_or_derived_schema_id")
        .put(ControllerRoute.REMOVE_DERIVED_SCHEMA, "remove_derived_schema")
        .put(ControllerRoute.MASTER_CONTROLLER, "master_controller")
        .put(ControllerRoute.LEADER_CONTROLLER, "leader_controller")
        .put(ControllerRoute.EXECUTION, "execution")
        .put(ControllerRoute.LAST_SUCCEED_EXECUTION_ID, "last_succeed_execution_id")
        .put(ControllerRoute.STORAGE_ENGINE_OVERHEAD_RATIO, "storage_engine_overhead_ratio")
        .put(ControllerRoute.ENABLE_THROTTLING, "enable_throttling")
        .put(ControllerRoute.ENABLE_MAX_CAPACITY_PROTECTION, "enable_max_capacity_protection")
        .put(ControllerRoute.ENABLE_QUOTA_REBALANCED, "enable_quota_rebalanced")
        .put(ControllerRoute.GET_ROUTERS_CLUSTER_CONFIG, "get_routers_cluster_config")
        .put(ControllerRoute.GET_ALL_MIGRATION_PUSH_STRATEGIES, "get_all_migration_push_strategies")
        .put(ControllerRoute.SET_MIGRATION_PUSH_STRATEGY, "set_migration_push_strategy")
        .put(ControllerRoute.CLUSTER_DISCOVERY, "cluster_discovery")
        .put(ControllerRoute.LIST_BOOTSTRAPPING_VERSIONS, "list_bootstrapping_versions")
        .put(ControllerRoute.OFFLINE_PUSH_INFO, "offline_push_info")
        .put(ControllerRoute.UPLOAD_PUSH_JOB_STATUS, "upload_push_job_status")
        .put(ControllerRoute.SEND_PUSH_JOB_DETAILS, "send_push_job_details")
        .put(ControllerRoute.SEND_HEARTBEAT_TIMESTAMP_TO_SYSTEM_STORE, "send_heartbeat_timestamp_to_system_store")
        .put(ControllerRoute.GET_HEARTBEAT_TIMESTAMP_FROM_SYSTEM_STORE, "get_heartbeat_timestamp_from_system_store")
        .put(ControllerRoute.ADD_VERSION, "add_version")
        .put(ControllerRoute.FUTURE_VERSION, "future_version")
        .put(ControllerRoute.BACKUP_VERSION, "backup_version")
        .put(ControllerRoute.SET_TOPIC_COMPACTION, "set_topic_compaction")
        .put(ControllerRoute.UPDATE_ACL, "update_acl")
        .put(ControllerRoute.GET_ACL, "get_acl")
        .put(ControllerRoute.DELETE_ACL, "delete_acl")
        .put(ControllerRoute.GET_DELETABLE_STORE_TOPICS, "get_deletable_store_topics")
        .put(ControllerRoute.GET_ALL_REPLICATION_METADATA_SCHEMAS, "get_all_replication_metadata_schemas")
        .put(ControllerRoute.GET_ONGOING_INCREMENTAL_PUSH_VERSIONS, "get_ongoing_incremental_push_versions")
        .put(ControllerRoute.GET_REPUSH_INFO, "get_repush_info")
        .put(ControllerRoute.WIPE_CLUSTER, "wipe_cluster")
        .put(ControllerRoute.COMPARE_STORE, "compare_store")
        .put(ControllerRoute.REPLICATE_META_DATA, "replicate_meta_data")
        .put(ControllerRoute.DATA_RECOVERY, "data_recovery")
        .put(ControllerRoute.PREPARE_DATA_RECOVERY, "prepare_data_recovery")
        .put(ControllerRoute.IS_STORE_VERSION_READY_FOR_DATA_RECOVERY, "is_store_version_ready_for_data_recovery")
        .put(ControllerRoute.GET_STALE_STORES_IN_CLUSTER, "get_stale_stores_in_cluster")
        .put(ControllerRoute.GET_STORES_IN_CLUSTER, "get_stores_in_cluster")
        .put(ControllerRoute.GET_STORES_FOR_COMPACTION, "get_stores_for_compaction")
        .put(ControllerRoute.REPUSH_STORE, "repush_store")
        .put(ControllerRoute.GET_STORE_LARGEST_USED_VERSION, "get_store_largest_used_version")
        .put(ControllerRoute.GET_DEAD_STORES, "get_dead_stores")
        .put(ControllerRoute.LIST_STORE_PUSH_INFO, "list_store_push_info")
        .put(ControllerRoute.GET_REGION_PUSH_DETAILS, "get_region_push_details")
        .put(ControllerRoute.GET_KAFKA_TOPIC_CONFIGS, "get_kafka_topic_configs")
        .put(ControllerRoute.UPDATE_KAFKA_TOPIC_LOG_COMPACTION, "update_kafka_topic_log_compaction")
        .put(ControllerRoute.UPDATE_KAFKA_TOPIC_RETENTION, "update_kafka_topic_retention")
        .put(ControllerRoute.UPDATE_KAFKA_TOPIC_MIN_IN_SYNC_REPLICA, "update_kafka_topic_min_in_sync_replica")
        .put(ControllerRoute.GET_ADMIN_TOPIC_METADATA, "get_admin_topic_metadata")
        .put(ControllerRoute.UPDATE_ADMIN_TOPIC_METADATA, "update_admin_topic_metadata")
        .put(ControllerRoute.UPDATE_ADMIN_OPERATION_PROTOCOL_VERSION, "update_admin_operation_protocol_version")
        .put(
            ControllerRoute.GET_ADMIN_OPERATION_VERSION_FROM_CONTROLLERS,
            "get_admin_operation_version_from_controllers")
        .put(ControllerRoute.GET_LOCAL_ADMIN_OPERATION_PROTOCOL_VERSION, "get_local_admin_operation_protocol_version")
        .put(ControllerRoute.DELETE_KAFKA_TOPIC, "delete_kafka_topic")
        .put(ControllerRoute.CREATE_STORAGE_PERSONA, "create_storage_persona")
        .put(ControllerRoute.GET_STORAGE_PERSONA, "get_storage_persona")
        .put(ControllerRoute.DELETE_STORAGE_PERSONA, "delete_storage_persona")
        .put(ControllerRoute.UPDATE_STORAGE_PERSONA, "update_storage_persona")
        .put(ControllerRoute.GET_STORAGE_PERSONA_ASSOCIATED_WITH_STORE, "get_storage_persona_associated_with_store")
        .put(ControllerRoute.GET_CLUSTER_STORAGE_PERSONAS, "get_cluster_storage_personas")
        .put(ControllerRoute.CLEANUP_INSTANCE_CUSTOMIZED_STATES, "cleanup_instance_customized_states")
        .put(ControllerRoute.REMOVE_STORE_FROM_GRAVEYARD, "remove_store_from_graveyard")
        .put(ControllerRoute.DELETE_UNUSED_VALUE_SCHEMAS, "delete_unused_value_schemas")
        .put(ControllerRoute.GET_INUSE_SCHEMA_IDS, "get_inuse_schema_ids")
        .put(ControllerRoute.VALIDATE_STORE_DELETED, "validate_store_deleted")
        .build();
    new VeniceDimensionTestFixture<>(
        ControllerRoute.class,
        VeniceMetricsDimensions.VENICE_CONTROLLER_ENDPOINT,
        expectedValues).assertAll();
  }
}
