#!/bin/bash

function set_base_script {
	PROJECT_NAME=$1
	BASE_SCRIPT="$BASE_DIR/$PROJECT_NAME/build/install/$PROJECT_NAME/bin/$PROJECT_NAME"
	
	if [ -e $BASE_SCRIPT ]; then
	        echo "BASE_SCRIPT exists: $BASE_SCRIPT"
	else
	        echo "BASE_SCRIPT does not exist: $BASE_SCRIPT"
	        echo "Did you forget to generate it? Run the following command to do so:"
	        echo ""
	        echo "./gradlew buildAll"
	        exit 1
	fi
}
