version: '3.8'

services:
  zookeeper:
    image: "venicedb/zookeeper:latest"
    container_name: zookeeper
    hostname: zookeeper
    healthcheck:
        test: ["CMD-SHELL", "echo ruok | nc zookeeper 2181"]
        start_period: 10s
        interval: 5s
        timeout: 5s
        retries: 5

  kafka:
    image: "venicedb/kafka:latest"
    container_name: kafka
    hostname: kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
        test: ["CMD-SHELL", "bash -x bin/kafka-topics.sh --bootstrap-server localhost:9092 --list"]
        start_period: 60s
        interval: 5s
        timeout: 20s
        retries: 5

  venice-controller:
    image: "venicedb/venice-controller:${TAG:-latest}"
    container_name: venice-controller
    hostname: venice-controller
    depends_on:
      kafka:
        condition: service_healthy
    healthcheck:
        test: ["CMD-SHELL", "sleep 5"]
        start_period: 20s
        interval: 5s
        timeout: 20s
        retries: 5

  venice-server:
    image: "venicedb/venice-server:${TAG:-latest}"
    container_name: venice-server
    hostname: venice-server
    depends_on:
      venice-controller:
        condition: service_healthy
    healthcheck:
        test: ["CMD-SHELL", "sleep 5"]
        start_period: 20s
        interval: 5s
        timeout: 20s
        retries: 5

  venice-router:
    image: "venicedb/venice-router:${TAG:-latest}"
    container_name: venice-router
    hostname: venice-router
    depends_on:
      venice-server:
        condition: service_healthy
    healthcheck:
        test: ["CMD-SHELL", "sleep 5"]
        start_period: 20s
        interval: 5s
        timeout: 20s
        retries: 5

  venice-client:
    image: "venicedb/venice-client:${TAG:-latest}"
    container_name: venice-client
    hostname: venice-client
    tty: true
    depends_on:
      venice-router:
        condition: service_healthy
