#!/bin/sh -e

echo 'Running pre-commit checks...'
[ -z "$(git diff --staged --name-only --diff-filter=d)" ] && exit 0
./gradlew spotlessApply
git diff --staged --name-only --diff-filter=d | xargs git add
