#!/bin/sh -e

echo 'Running pre-commit checks...'
[ -z "$(git diff --staged --name-only --diff-filter=d)" ] && exit 0
./gradlew spotlessApply
./gradlew generateGHCI && git add .github/workflows/VeniceCI-E2ETests.yml
git diff --staged --name-only --diff-filter=d | xargs git add
