package com.linkedin.venice.guid;

import com.linkedin.venice.kafka.protocol.GUID;
import java.nio.ByteBuffer;
import java.util.UUID;


/**
 * A GUID generator for Declaration of Leadership (DoL) control messages.
 * 
 * <p>Uses {@link java.util.UUID#nameUUIDFromBytes(byte[])} to generate a type 3 UUID that will
 * not collide with:
 * <ul>
 *   <li>User data GUIDs (type 4, generated by {@link JavaUtilGuidV4Generator})</li>
 *   <li>Heartbeat control message GUIDs (type 3, generated by {@link HeartbeatGuidV3Generator})</li>
 * </ul>
 * 
 * <p>DoL messages use a distinct GUID to clearly identify leadership declaration messages
 * during the leader handover process. This allows replicas to distinguish DoL messages from
 * regular heartbeat messages and user data.
 */
public class DolGuidGenerator implements GuidGenerator {
  private static DolGuidGenerator instance;

  private DolGuidGenerator() {
  }

  public static synchronized DolGuidGenerator getInstance() {
    if (instance == null) {
      instance = new DolGuidGenerator();
    }
    return instance;
  }

  @Override
  public GUID getGuid() {
    UUID javaUtilUuid = UUID.nameUUIDFromBytes("declarationOfLeadershipControlMessage".getBytes());
    GUID guid = new GUID();
    byte[] guidBytes = ByteBuffer.allocate(16)
        .putLong(javaUtilUuid.getMostSignificantBits())
        .putLong(javaUtilUuid.getLeastSignificantBits())
        .array();
    guid.bytes(guidBytes);
    return guid;
  }
}
