title: Venice
remote_theme: just-the-docs/just-the-docs
favicon_ico: "/assets/style/favicon.ico"

color_scheme: dark

nav_external_links:
  - title: Javadoc
    url: ./javadoc/index.html
    hide_icon: false

exclude:
  # javadoc/legal has some markdowns that get picked up by jekyll/just-the-docs
  - javadoc/legal
  - vendor/

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "✏️ Edit this page on GitHub"
gh_edit_repository: "https://github.com/linkedin/venice" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "edit" # "tree" or "edit" if you want the user to jump into the editor immediately
