title: Venice
remote_theme: just-the-docs/just-the-docs
favicon_ico: "/assets/style/favicon.ico"

nav_external_links:
  - title: Javadoc
    url: ./javadoc/index.html
    hide_icon: false

exclude:
  # javadoc/legal has some markdowns that get picked up by jekyll/just-the-docs
  - javadoc/legal
  - vendor/
