type=hadoopJava
job.class=com.linkedin.venice.hadoop.KafkaPushJob
classpath=libs/*
azkaban.should.proxy=true
user.to.proxy=voldtest
input.path=/user/voldtest/h2v_test/100k
avro.key.field=key
avro.value.field=value

# NEVER USE KAFKA CORP CLUSTER FOR TESTING
# FOR KAFKA, CORP IS PROD, AS THE INGRAPH DATA IS RELAYED
# BACK FROM PROD TO CORP FOR INGRAPH AND OTHER ALERTING

# NEVER USE OTHER KAFKA CLUSTERS AS WELL, AS KAFKA
# PRODUCER WE USE PRODUCE MESSAGES THAT CAN'T BE
# UNDERSTOOD BY OLDER KAFKA CLUSTERS AND IT CRASHES THEM.

venice.urls=http://ltx1-app1085.stg.linkedin.com:1689,http://ltx1-app1325.stg.linkedin.com:1689
venice.store.name=venice_h2v_test_100k_1
venice.store.owners=venice-eng@linkedin.com
cluster.name=test-cluster