type=hadoopJava
job.class=com.linkedin.venice.hadoop.KafkaPushJob
classpath=libs/*
azkaban.should.proxy=true
user.to.proxy=voldtest
input.path=/user/voldtest/h2v_test/500m
avro.key.field=key
avro.value.field=value

# NEVER USE KAFKA CORP CLUSTER FOR TESTING
# FOR KAFKA, CORP IS PROD, AS THE INGRAPH DATA IS RELAYED
# BACK FROM PROD TO CORP FOR INGRAPH AND OTHER ALERTING

# NEVER USE OTHER KAFKA CLUSTERS AS WELL, AS KAFKA
# PRODUCER WE USE PRODUCE MESSAGES THAT CAN'T BE
# UNDERSTOOD BY OLDER KAFKA CLUSTERS AND IT CRASHES THEM.

venice.urls=http://ltx1-app1005.stg.linkedin.com:1576,http://ltx1-app1365.stg.linkedin.com:1576,http://ltx1-app1405.stg.linkedin.com:1576
venice.store.name=venice_h2v_test_500m_2
venice.store.owners=venice-eng@linkedin.com
cluster.name=test-cluster