type=hadoopJava
job.class=com.linkedin.venice.hadoop.KafkaPushJob
classpath=libs/*
azkaban.should.proxy=true
user.to.proxy=voldteei
input.path=/user/voldteei/h2v_test/500m
avro.key.field=key
avro.value.field=value

# NEVER USE KAFKA CORP CLUSTER FOR TESTING
# FOR KAFKA, CORP IS PROD, AS THE INGRAPH DATA IS RELAYED
# BACK FROM PROD TO CORP FOR INGRAPH AND OTHER ALERTING

# NEVER USE OTHER KAFKA CLUSTERS AS WELL, AS KAFKA
# PRODUCER WE USE PRODUCE MESSAGES THAT CAN'T BE
# UNDERSTOOD BY OLDER KAFKA CLUSTERS AND IT CRASHES THEM.

venice.urls=https://ltx1-app1005.stg.linkedin.com:1578
venice.store.name=venice_h2v_test_500m
venice.store.owners=venice-eng@linkedin.com
venice.ssl.enable=true
cluster.name=test-cluster