/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.linkedin.venice.meta.systemstore.schemas;

@SuppressWarnings("all")
public class StoreVersionState extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"StoreVersionState\",\"namespace\":\"com.linkedin.venice.meta.systemstore.schemas\",\"fields\":[{\"name\":\"versionNumber\",\"type\":\"int\"},{\"name\":\"pushJobId\",\"type\":\"string\"},{\"name\":\"partitionCount\",\"type\":\"int\"},{\"name\":\"creationTime\",\"type\":\"long\"},{\"name\":\"chunkingEnabled\",\"type\":\"boolean\"},{\"name\":\"compressionStrategy\",\"type\":\"string\"},{\"name\":\"leaderFollowerModelEnabled\",\"type\":\"boolean\"},{\"name\":\"pushType\",\"type\":\"string\"},{\"name\":\"status\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"partitionerConfig\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"PartitionerConfig\",\"fields\":[{\"name\":\"amplificationFactor\",\"type\":\"int\"},{\"name\":\"partitionerClass\",\"type\":\"string\"},{\"name\":\"partitionerParams\",\"type\":{\"type\":\"map\",\"values\":\"string\"}}]}],\"default\":null}]}");
  public int versionNumber;
  public java.lang.CharSequence pushJobId;
  public int partitionCount;
  public long creationTime;
  public boolean chunkingEnabled;
  public java.lang.CharSequence compressionStrategy;
  public boolean leaderFollowerModelEnabled;
  public java.lang.CharSequence pushType;
  public java.lang.CharSequence status;
  public com.linkedin.venice.meta.systemstore.schemas.PartitionerConfig partitionerConfig;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return versionNumber;
    case 1: return pushJobId;
    case 2: return partitionCount;
    case 3: return creationTime;
    case 4: return chunkingEnabled;
    case 5: return compressionStrategy;
    case 6: return leaderFollowerModelEnabled;
    case 7: return pushType;
    case 8: return status;
    case 9: return partitionerConfig;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: versionNumber = (java.lang.Integer)value$; break;
    case 1: pushJobId = (java.lang.CharSequence)value$; break;
    case 2: partitionCount = (java.lang.Integer)value$; break;
    case 3: creationTime = (java.lang.Long)value$; break;
    case 4: chunkingEnabled = (java.lang.Boolean)value$; break;
    case 5: compressionStrategy = (java.lang.CharSequence)value$; break;
    case 6: leaderFollowerModelEnabled = (java.lang.Boolean)value$; break;
    case 7: pushType = (java.lang.CharSequence)value$; break;
    case 8: status = (java.lang.CharSequence)value$; break;
    case 9: partitionerConfig = (com.linkedin.venice.meta.systemstore.schemas.PartitionerConfig)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}
