name: Auto Release Notes

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  generate-release-note:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Changelog
        run: |
          prev_tag=$(git for-each-ref --sort=creatordate --format '%(refname:lstrip=2)' refs/tags |  tail -2 | head -1)
          curr_tag=$(git for-each-ref --sort=creatordate --format '%(refname:lstrip=2)' refs/tags | tail -1)
          echo "Previous tag: ${prev_tag}"
          echo "Current tag: ${curr_tag}"
          for commit in $(git rev-list "$prev_tag..$curr_tag"); do
            echo -n "  -  " >> changelog.txt
            git --no-pager log --no-decorate "$commit^..$commit" --oneline >> changelog.txt
          done

      - name: Publish GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create $GITHUB_REF_NAME \
              --title "$GITHUB_REF_NAME Release" \
              --notes-file changelog.txt

