package com.linkedin.venice.controller;

/**
 * Accessor user to get/update the last execution id and the generated id from a storage.
 */
public interface ExecutionIdAccessor {
  /**
   * Get the id for the last succeed operation in the given cluster.
   */
  public Long getLastSucceedExecutionId(String clusterName);

  /**
   * Update the the id of the last succeed operation in the given cluster.
   */
  public void updateLastSucceedExecutionId(String clusterName, Long lastSucceedExecutionId);

  /**
   * Get the last id which is generated by execution tracker in the give cluster.
   */
  public Long getLastGeneratedExecutionId(String clusterName);

  /**
   * Update the last id which is generated by execution tracker in the given cluster.
   */
  public void updateLastGeneratedExecutionId(String clusterName, Long lastGeneratedExecutionId);
}
