package com.linkedin.venice.controller;

import java.util.Map;


/**
 * Accessor user to get/update the last execution id and the generated id from a storage.
 */
public interface ExecutionIdAccessor {
  /**
   * Get the id for the last succeed operation in the given cluster.
   */
  public Long getLastSucceededExecutionId(String clusterName);

  /**
   * Update the the id of the last succeed operation in the given cluster.
   */
  public void updateLastSucceededExecutionId(String clusterName, Long lastSucceedExecutionId);

  /**
   * Get the execution id map that contains the last succeeded operation in the given cluster for each store.
   */
  public Map<String, Long> getLastSucceededExecutionIdMap(String clusterName);

  /**
   * Update the the execution id map that contains the last succeeded operation in the given cluster for each store.
   */
  public void updateLastSucceededExecutionIdMap(String clusterName, String storeName, Long lastSucceededExecutionId);

  /**
   * Get the last id which is generated by execution tracker in the give cluster.
   */
  public Long getLastGeneratedExecutionId(String clusterName);

  /**
   * Update the last id which is generated by execution tracker in the given cluster.
   */
  public void updateLastGeneratedExecutionId(String clusterName, Long lastGeneratedExecutionId);
}
